### ISSUE TITLE
Small slime on a farmland

### ISSUE THREAD

**Issue by LuckyStrikeOriginal** [iChun/Morph#1051]
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2019-10-11 21:58:15 EEST
Description: Ticking player

java.lang.NullPointerException
    at me.ichun.mods.morph.common.handler.PlayerMorphHandler.setPlayerSize(PlayerMorphHandler.java:449)
    at me.ichun.mods.morph.common.core.EventHandlerServer.onPlayerTick(EventHandlerServer.java:204)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2001_EventHandlerServer_onPlayerTick_PlayerTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:365)
    at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:190)
    at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:382)
    at net.minecraft.network.NetHandlerPlayServer.update(NetHandlerPlayServer.java:173)
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.update(NetworkDispatcher.java:209)
    at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:285)
    at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:180)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:790)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:745)

https://paste.dimdev.org/ewijuradev.mccrash

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
