### ISSUE TITLE
Animation crashes my game

### ISSUE THREAD

**Issue by HOTE2** [iChun/Morph#1062]
I play on a server (1.7.10) and when I morph my friends crash or I crash if I open inv or do f5. I am no expert but from what I can tell it's prob the animation.
Here's the crash report:
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2/9/20 4:29 PM
Description: Rendering entity in world

java.lang.ClassCastException: morph.client.render.RenderMorph cannot be cast to net.minecraft.client.renderer.entity.RenderPlayer
	at com.legacy.aether.client.AetherClientEvents.onRenderAccessories(AetherClientEvents.java:251)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_151_AetherClientEvents_onRenderAccessories_Post.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.client.renderer.entity.RendererLivingEntity.func_76986_a(RendererLivingEntity.java:281)
	at morph.common.core.EventHandler.onRenderPlayer(EventHandler.java:599)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_95_EventHandler_onRenderPlayer_Pre.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:131)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:521)
	at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:293)
	at net.minecraft.client.renderer.entity.RenderManager.func_147936_a(RenderManager.java:271)
	at net.minecraft.client.renderer.entity.RenderManager.func_147937_a(RenderManager.java:244)
	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:471)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1224)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.legacy.aether.client.AetherClientEvents.onRenderAccessories(AetherClientEvents.java:251)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_151_AetherClientEvents_onRenderAccessories_Post.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.client.renderer.entity.RendererLivingEntity.func_76986_a(RendererLivingEntity.java:281)
	at morph.common.core.EventHandler.onRenderPlayer(EventHandler.java:599)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_95_EventHandler_onRenderPlayer_Pre.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:131)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:521)

-- Entity being rendered --
Details:
	Entity Type: null (net.minecraft.client.entity.EntityClientPlayerMP)
	Entity ID: 2026
	Entity Name: HOTE2
	Entity's Exact location: -391.35, 68.59, 476.15
	Entity's Block location: World: (-392,68,476), Chunk: (at 8,4,12 in -25,29; contains blocks -400,0,464 to -385,255,479), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.client.renderer.entity.RenderPlayer@647347f4
	Location: 0.00,0.00,0.00 - World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: 37.184544
	Delta: 0.08229375
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:293)
	at net.minecraft.client.renderer.entity.RenderManager.func_147936_a(RenderManager.java:271)
	at net.minecraft.client.renderer.entity.RenderManager.func_147937_a(RenderManager.java:244)
	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:471)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1224)

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [EntityClientPlayerMP['HOTE2'/2026, l='MpServer', x=-391.35, y=68.59, z=476.15], EntityOtherPlayerMP['Scorsonaire_'/310, l='MpServer', x=-397.56, y=78.00, z=476.66]]
	Chunk stats: MultiplayerChunkCache: 418, 418
	Level seed: 0
	Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-419,64,838), Chunk: (at 13,4,6 in -27,52; contains blocks -432,0,832 to -417,255,847), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
	Level time: 1391282 game time, 1396686 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 20 total; [EntityHat['unknown'/577, l='MpServer', x=-391.35, y=68.62, z=476.15], EntityTrail['unknown'/579, l='MpServer', x=-391.35, y=68.62, z=476.15], EntityPainting['Painting'/2189, l='MpServer', x=-394.50, y=79.50, z=471.06], EntityPainting['Painting'/2190, l='MpServer', x=-399.00, y=79.50, z=471.06], EntityClientPlayerMP['HOTE2'/2026, l='MpServer', x=-391.35, y=68.59, z=476.15], EnchantedCow['Enchanted Golden Apple Cow'/2191, l='MpServer', x=-398.47, y=68.00, z=474.09], EnchantedCow['Enchanted Golden Apple Cow'/2192, l='MpServer', x=-399.28, y=68.00, z=475.41], EntityPainting['Painting'/2193, l='MpServer', x=-392.06, y=80.00, z=473.00], EntityLunaMoth['Moth'/2194, l='MpServer', x=-377.35, y=76.48, z=471.18], EntityBat['Bat'/2780, l='MpServer', x=-401.16, y=52.00, z=516.16], Cricket['Cricket'/2791, l='MpServer', x=-420.72, y=71.00, z=472.97], EntityOtherPlayerMP['Scorsonaire_'/310, l='MpServer', x=-397.56, y=78.00, z=476.66], EntityTrail['unknown'/10665, l='MpServer', x=-397.56, y=78.00, z=476.66], EntityHat['unknown'/10666, l='MpServer', x=-397.56, y=78.00, z=476.66], WormMedium['Medium Worm'/2222, l='MpServer', x=-358.50, y=64.92, z=412.50], EntityPainting['Painting'/2189, l='MpServer', x=-394.50, y=79.50, z=471.06], EntityPainting['Painting'/2190, l='MpServer', x=-399.00, y=79.50, z=471.06], EntityOtherPlayerMP['Scorsonaire_'/310, l='MpServer', x=-397.31, y=59.00, z=480.41], EntityPainting['Painting'/2193, l='MpServer', x=-392.06, y=80.00, z=473.00], EntityOtherPlayerMP['Scorsonaire_'/310, l='MpServer', x=-397.56, y=78.00, z=476.66]]
	Retry entities: 0 total; []
	Server brand: kcauldron,cauldron,craftbukkit,mcpc,fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 596394328 bytes (568 MB) / 1324875776 bytes (1263 MB) up to 2863661056 bytes (2731 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3072m -Xms256m -XX:PermSize=256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 96
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 34 mods loaded, 34 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJA	DamageIndicatorsMod{3.3.2} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.3.2.jar) 
	UCHIJA	aether_legacy{v1.0.0} [Aether Legacy] (aether_legacy-1.7.10-v1.0.0.jar) 
	UCHIJA	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x.jar) 
	UCHIJA	BattleTowers{1.5.1} [Battle Towers] (BattleTowers-1.7.10.jar) 
	UCHIJA	BiblioCraft{1.11.5} [BiblioCraft] (BiblioCraft[v1.11.5][MC1.7.10].jar) 
	UCHIJA	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.2308-universal.jar) 
	UCHIJA	bookshelf{1.0.4.187} [Bookshelf] (Bookshelf-1.7.10-1.0.4.187.jar) 
	UCHIJA	BuildCraft|Core{7.1.23} [BuildCraft] (buildcraft-7.1.23.jar) 
	UCHIJA	BuildCraft|Transport{7.1.23} [BC Transport] (buildcraft-7.1.23.jar) 
	UCHIJA	BuildCraft|Factory{7.1.23} [BC Factory] (buildcraft-7.1.23.jar) 
	UCHIJA	BuildCraft|Silicon{7.1.23} [BC Silicon] (buildcraft-7.1.23.jar) 
	UCHIJA	BuildCraft|Robotics{7.1.23} [BC Robotics] (buildcraft-7.1.23.jar) 
	UCHIJA	BuildCraft|Energy{7.1.23} [BC Energy] (buildcraft-7.1.23.jar) 
	UCHIJA	BuildCraft|Builders{7.1.23} [BC Builders] (buildcraft-7.1.23.jar) 
	UCHIJA	DynamicLights{1.3.9a} [Dynamic Lights] (Dynamic+Lights-1.3.9a-MC1.7.10.jar) 
	UCHIJA	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) 
	UCHIJA	iChunUtil{4.2.3} [iChunUtil] (iChunUtil-4.2.3.jar) 
	UCHIJA	Hats{4.0.1} [Hats] (Hats-4.0.1.jar) 
	UCHIJA	headcrumbs{1.7.4} [Headcrumbs] (Headcrumbs-1.7.4.jar) 
	UCHIJA	InventoryPets{1.5.2} [Inventory Pets] (inventorypets-1.7.10-1.5.2-universal.jar) 
	UCHIJA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCHIJA	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCHIJA	Morph{0.9.2} [Morph] (Morph-Beta-0.9.2.jar) 
	UCHIJA	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) 
	UCHIJA	OreSpawn{1.7.10.20.3} [OreSpawn] (orespawn-1.7.10-20.3.zip) 
	UCHIJA	PortalGun{4.0.0-beta-6} [PortalGun] (PortalGun-4.0.0-beta-6-fix-1.jar) 
	UCHIJA	RedstonePasteMod{1.6.2} [Redstone Paste] (RedstonePasteMod-1.7.10-1.6.2.jar) 
	UCHIJA	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
	UCHIJA	xaerominimap{20.2.0} [Xaero's Minimap] (Xaeros_Minimap_20.2.0_Forge_1.7.10.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 441.66' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'
	Launched Version: forge-10.13.4.1614
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 441.66, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
Thanks for any help

**Comment by iChun** [comment]
It's a conflict with the aether mod but also on version 1.7.10, just FYI. I
won't be fixing this.

**Comment by HOTE2** [comment]
No worries thanks for the help :)
