### ISSUE TITLE
server crash due to NPE in AbilitySunburn

### ISSUE THREAD

**Issue by LemADEC** [iChun/Morph#1075]
As of Morph-1.12.2-7.2.0 + iChunUtil-1.12.2-7.2.2, an NPE is causing a server crash in the sunburn ability.

```
java.lang.NullPointerException: Exception in server tick loop
	at net.minecraft.entity.EntityLivingBase.func_184606_a_(EntityLivingBase.java:481)
	at net.minecraft.entity.player.EntityPlayer.func_184201_a(EntityPlayer.java:2180)
	at me.ichun.mods.morph.api.ability.type.AbilitySunburn.tick(AbilitySunburn.java:70)
	at me.ichun.mods.morph.common.morph.MorphInfo.tick(MorphInfo.java:136)
	at me.ichun.mods.morph.common.core.EventHandlerServer.onServerTick(EventHandlerServer.java:176)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_788_EventHandlerServer_onServerTick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.forgeBridge$post(EventBus.java:753)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:703)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by iChun** [comment]
I've tried to fix it in 7.2.1. Will be closing this in the meantime, feel free to reopen if it's not fixed.
