### ISSUE TITLE
Morph makes client crash

### ISSUE THREAD

**Issue by TheSatanicFlame** [iChun/Morph#1172]
After removing a mod from our server, when a player tries to open the morph menu, their client will crash.

we're on 1.16.5

**Comment by iChun** [comment]
Always attach a crash log when reporting crashes. I cannot help or fix it
without one.

**Comment by Copernicle** [comment]
I have the same issue. This is forge, 1.16.5
Here is MY Crash Report (Copied from latest.log)
NOTE: I have many mods installed. The game crashes ONLY for multiplayer and the mod works fine in singleplayer.
I can recreate this crash by connecting to my server, and pressing brackets. (The server is in offline mode for networking reasons.)

Time: 2/13/22 7:34 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.util.text.TextProcessing.func_238340_a_(SourceFile:88) ~[?:?] {re:classloading}
	at net.minecraft.util.text.TextProcessing.func_238339_a_(SourceFile:84) ~[?:?] {re:classloading}
	at net.minecraft.util.text.TextProcessing.func_238346_c_(SourceFile:80) ~[?:?] {re:classloading}
	at net.minecraft.client.util.BidiReorder.func_244289_a(SourceFile:66) ~[?:?] {re:classloading}
	at net.minecraft.util.text.ITextComponent.func_230534_b_(SourceFile:112) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.util.text.ITextComponent.func_230439_a_(SourceFile:79) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.client.util.BidiReorder.func_244290_a(SourceFile:65) ~[?:?] {re:classloading}
	at net.minecraft.client.util.BidiReorderer.func_243508_a(SourceFile:16) ~[?:?] {re:classloading}
	at net.minecraft.client.resources.ClientLanguageMap.func_241870_a(ClientLanguageMap.java:79) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.util.text.TextComponent.func_241878_f(SourceFile:61) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.client.gui.FontRenderer.func_243246_a(SourceFile:78) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at me.ichun.mods.morph.client.core.HudHandler.drawSelector(HudHandler.java:785) ~[morph:10.1.0] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at me.ichun.mods.morph.client.core.HudHandler.onIngameGuiPost(HudHandler.java:1328) ~[morph:10.1.0] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.eventbus.ASMEventHandler_432_HudHandler_onIngameGuiPost_Post.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.client.gui.ForgeIngameGui.post(ForgeIngameGui.java:832) ~[forge:?] {re:mixin,xf:fml:xaerominimap:xaero_forgeingamegui_render,re:classloading,xf:fml:xaerominimap:xaero_forgeingamegui_render,pl:mixin:APP:morph.mixins.json:ForgeIngameGuiMixin,pl:mixin:A}
	at net.minecraftforge.client.gui.ForgeIngameGui.func_238445_a_(ForgeIngameGui.java:222) ~[forge:?] {re:mixin,xf:fml:xaerominimap:xaero_forgeingamegui_render,re:classloading,xf:fml:xaerominimap:xaero_forgeingamegui_render,pl:mixin:APP:morph.mixins.json:ForgeIngameGuiMixin,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:472) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:StoreProjectionMatrixMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5-forge-36.2.26.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.26.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.util.text.TextProcessing.func_238340_a_(SourceFile:88) ~[?:?] {re:classloading}
	at net.minecraft.util.text.TextProcessing.func_238339_a_(SourceFile:84) ~[?:?] {re:classloading}
	at net.minecraft.util.text.TextProcessing.func_238346_c_(SourceFile:80) ~[?:?] {re:classloading}
	at net.minecraft.client.util.BidiReorder.func_244289_a(SourceFile:66) ~[?:?] {re:classloading}
	at net.minecraft.util.text.ITextComponent.func_230534_b_(SourceFile:112) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.util.text.ITextComponent.func_230439_a_(SourceFile:79) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.client.util.BidiReorder.func_244290_a(SourceFile:65) ~[?:?] {re:classloading}
	at net.minecraft.client.util.BidiReorderer.func_243508_a(SourceFile:16) ~[?:?] {re:classloading}
	at net.minecraft.client.resources.ClientLanguageMap.func_241870_a(ClientLanguageMap.java:79) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.util.text.TextComponent.func_241878_f(SourceFile:61) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.client.gui.FontRenderer.func_243246_a(SourceFile:78) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at me.ichun.mods.morph.client.core.HudHandler.drawSelector(HudHandler.java:785) ~[morph:10.1.0] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at me.ichun.mods.morph.client.core.HudHandler.onIngameGuiPost(HudHandler.java:1328) ~[morph:10.1.0] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.eventbus.ASMEventHandler_432_HudHandler_onIngameGuiPost_Post.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.client.gui.ForgeIngameGui.post(ForgeIngameGui.java:832) ~[forge:?] {re:mixin,xf:fml:xaerominimap:xaero_forgeingamegui_render,re:classloading,xf:fml:xaerominimap:xaero_forgeingamegui_render,pl:mixin:APP:morph.mixins.json:ForgeIngameGuiMixin,pl:mixin:A}
	at net.minecraftforge.client.gui.ForgeIngameGui.func_238445_a_(ForgeIngameGui.java:222) ~[forge:?] {re:mixin,xf:fml:xaerominimap:xaero_forgeingamegui_render,re:classloading,xf:fml:xaerominimap:xaero_forgeingamegui_render,pl:mixin:APP:morph.mixins.json:ForgeIngameGuiMixin,pl:mixin:A}
-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Copernicle'/381, l='ClientLevel', x=107.24, y=65.00, z=90.74]]
	Chunk stats: Client Chunk Cache: 729, 479
	Level dimension: minecraft:overworld
	Level spawn location: World: (74,78,128), Chunk: (at 10,4,0 in 4,8; contains blocks 64,0,128 to 79,255,143), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 295044 game time, 295044 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:447) ~[?:?] {re:mixin,xf:fml:xaerominimap:xaero_clientworldclass,pl:runtimedistcleaner:A,re:classloading,xf:fml:xaerominimap:xaero_clientworldclass,pl:mixin:APP:mixins.sndctrl.json:MixinClientWorld,pl:mixin:APP:create.mixins.json:BreakProgressMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2031) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:628) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5-forge-36.2.26.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.26.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 5.13.0-28-generic
	Java Version: 1.8.0_202, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3579162864 bytes (3413 MB) / 5704253440 bytes (5440 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 4
	JVM Flags: 9 total; -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.26.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.26.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.26.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.26.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.26.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.26
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.26-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		TConstruct-1.16.5-3.3.3.332.jar                   |Tinkers' Construct            |tconstruct                    |3.3.3.332           |DONE      |Manifest: NOSIGNATURE
		mcw-bridges-1.0.4-mc1.16.4.jar                    |Macaw's Bridges               |mcwbridges                    |1.0.4               |DONE      |Manifest: NOSIGNATURE
		repurposed_structures_forge-3.4.6+1.16.5.jar      |Repurposed Structures         |repurposed_structures         |3.4.6+1.16.5        |DONE      |Manifest: NOSIGNATURE
		pamhc2trees-1.16.3-1.0.0.jar                      |Pam's HarvestCraft 2 Fruit Tre|pamhc2trees                   |1.0.0               |DONE      |Manifest: NOSIGNATURE
		BiomesOPlenty-1.16.5-13.1.0.480-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.5-13.1.0.480   |DONE      |Manifest: NOSIGNATURE
		pamhc2crops-1.16.3-1.0.1.jar                      |Pam's HarvestCraft 2 Crops    |pamhc2crops                   |version             |DONE      |Manifest: NOSIGNATURE
		mcw-trapdors-1.0.0-mc1.16.4.jar                   |Macaw's Trapdoors             |mcwtrpdoors                   |1.0.0               |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.145.jar                          |Just Enough Items             |jei                           |7.7.1.145           |DONE      |Manifest: NOSIGNATURE
		mcw-windows-1.0.2-mc1.16.4.jar                    |Macaw's Windows               |mcwwindows                    |1.0.2               |DONE      |Manifest: NOSIGNATURE
		sleeping_bags-1.16.4-1.0.1.jar                    |Sleeping Bags                 |sleeping_bags                 |1.16.4-1.0.1        |DONE      |Manifest: NOSIGNATURE
		flywheel-1.16-0.2.5.jar                           |Flywheel                      |flywheel                      |1.16-0.2.5          |DONE      |Manifest: NOSIGNATURE
		Mantle-1.16.5-1.6.157.jar                         |Mantle                        |mantle                        |1.6.157             |DONE      |Manifest: NOSIGNATURE
		create-mc1.16.5_v0.3.2g.jar                       |Create                        |create                        |v0.3.2g             |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_22.1.2_Forge_1.16.5.jar            |Xaero's Minimap               |xaerominimap                  |22.1.2              |DONE      |Manifest: NOSIGNATURE
		ForgeEndertech-1.16.4-7.0.8.0-build.0028.jar      |Forge Endertech               |forgeendertech                |7.0.8.0             |DONE      |Manifest: NOSIGNATURE
		AdLods-1.16.4-4.1.2.0-build.0027.jar              |Large Ore Deposits            |adlods                        |4.1.2.0             |DONE      |Manifest: NOSIGNATURE
		pamhc2foodcore-1.16.3-1.0.0.jar                   |Pam's HarvestCraft 2 Food Core|pamhc2foodcore                |version             |DONE      |Manifest: NOSIGNATURE
		appliedenergistics2-8.4.6.jar                     |Applied Energistics 2         |appliedenergistics2           |8.4.6               |DONE      |Manifest: 95:58:cc:83:9d:a8:fa:4f:e9:f3:54:90:66:61:c8:ae:9c:08:88:11:52:52:df:2d:28:5f:05:d8:28:57:0f:98
		buildersaddition-1.16.3-20201028b(1).jar          |Builders Crafts & Addition    |buildersaddition              |1.16.3-20201028b    |DONE      |Manifest: NOSIGNATURE
		worldedit-forge-mc1.16.3-7.2.2-dist.jar           |WorldEdit                     |worldedit                     |7.2.2+fc3c499       |DONE      |Manifest: NOSIGNATURE
		randompatches-2.4.4-forge.jar                     |RandomPatches                 |randompatches                 |2.4.4-forge         |DONE      |Manifest: 92:f6:29:d4:09:89:f5:f5:98:5e:20:34:31:d0:7b:58:22:06:bd:a5:d1:6a:92:6e:ac:3d:8d:18:c5:b2:5b:d7
		mcws-roofs-2.0.0-mc1.16.4.jar                     |Macaw's Roofs                 |mcwroofs                      |2.0.0               |DONE      |Manifest: NOSIGNATURE
		InventoryProfilesNext-forge-1.16-1.3.2.jar        |Inventory Profiles Next       |inventoryprofilesnext         |1.3.2               |DONE      |Manifest: NOSIGNATURE
		mcw-doors-1.0.1fix-mc1.16.4.jar                   |Macaw's Doors                 |mcwdoors                      |1.0.1               |DONE      |Manifest: NOSIGNATURE
		cc-tweaked-1.16.4-1.94.0.jar                      |CC: Tweaked                   |computercraft                 |1.94.0              |DONE      |Manifest: NOSIGNATURE
		travellersboots-1.16.x-1.4.3.jar                  |Traveller's Boots             |travellersboots               |1.4.3               |DONE      |Manifest: NOSIGNATURE
		Hwyla-forge-1.10.11-B78_1.16.2.jar                |Waila                         |waila                         |1.10.11-B78_1.16.2  |DONE      |Manifest: NOSIGNATURE
		cloth-config-4.14.54-forge.jar                    |Cloth Config v4 API           |cloth-config                  |4.14.54             |DONE      |Manifest: NOSIGNATURE
		iChunUtil-1.16.5-10.5.1.jar                       |iChunUtil                     |ichunutil                     |10.5.1              |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.26-universal.jar                |Forge                         |forge                         |36.2.26             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		FastLeafDecay-v25.2.jar                           |FastLeafDecay                 |fastleafdecay                 |v25.2               |DONE      |Manifest: NOSIGNATURE
		CosmeticArmorReworked-1.16.4-v1.jar               |CosmeticArmorReworked         |cosmeticarmorreworked         |1.16.4-v1           |DONE      |Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		Morph-1.16.5-10.1.0.jar                           |Morph                         |morph                         |10.1.0              |DONE      |Manifest: NOSIGNATURE
		lumberjack-2.1.4.jar                              |LumberJack                    |lumberjack                    |2.1.4               |DONE      |Manifest: NOSIGNATURE
		JEIEnchantmentInfo-1.16.4-1.2.1.jar               |JEI Enchantment Info          |jeienchantmentinfo            |1.16.4-1.2.1        |DONE      |Manifest: NOSIGNATURE
		DynamicSurroundings-1.16.5-4.0.5.0.jar            |Dynamic Surroundings        |dsurround                     |4.0.5.0             |DONE      |Manifest: NOSIGNATURE
		ironchest-1.16.4-11.2.10.jar                      |Iron Chests                   |ironchest                     |1.16.4-11.2.10      |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 3db022c1-1332-42c4-833e-50ffc8d56edd
	Launched Version: 1.16.5-forge-36.2.26
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Radeon RX 580 Series (POLARIS10, DRM 3.41.0, 5.13.0-28-generic, LLVM 12.0.0) GL version 4.6 (Compatibility Profile) Mesa 21.0.3, AMD
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, file/Screw Microsoft
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-3330 CPU @ 3.00GHz
[13Feb2022 19:34:32.093] [Render thread/INFO] [STDOUT/]: [net.minecraft.util.registry.Bootstrap:func_179870_a:123]: #@!@# Game crashed! Crash report saved to: #@!@# /home/me/.minecraft/crash-reports/crash-2022-02-13_19.34.32-client.txt

**Comment by iChun** [comment]
@Copernicle I have fixed your crash, slated for the next update.

@TheSatanicFlame I cannot fix your crash without a log, I will be closing this issue.
