### ISSUE TITLE
Morph mod crashing in server

### ISSUE THREAD

**Issue by LifeOrReality** [iChun/Morph#1209]
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 17/05/22 22:06
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
	at vazkii.botania.client.core.handler.ContributorFancinessHandler.render(ContributorFancinessHandler.java:48) ~[?:1.16.5-420.2] {re:classloading}
	at vazkii.botania.client.core.handler.ContributorFancinessHandler.func_225628_a_(ContributorFancinessHandler.java:32) ~[?:1.16.5-420.2] {re:classloading}
	at net.minecraft.client.renderer.entity.LivingRenderer.func_225623_a_(LivingRenderer.java:204) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default,re:mixin,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.entity.PlayerRenderer.func_225623_a_(PlayerRenderer.java:64) ~[?:?] {re:mixin,xf:fml:forge:crossbows.2,pl:runtimedistcleaner:A,re:classloading,xf:fml:forge:crossbows.2,pl:mixin:APP:aoa3.mixins.json:client.patch.PlayerRendererMixin,pl:mixin:APP:morph.mixins.json:PlayerRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.PlayerRenderer.func_225623_a_(PlayerRenderer.java:41) ~[?:?] {re:mixin,xf:fml:forge:crossbows.2,pl:runtimedistcleaner:A,re:classloading,xf:fml:forge:crossbows.2,pl:mixin:APP:aoa3.mixins.json:client.patch.PlayerRendererMixin,pl:mixin:APP:morph.mixins.json:PlayerRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:311) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.gui.screen.inventory.InventoryScreen.func_241611_a_(SourceFile:149) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.gui.screen.inventory.InventoryScreen$$Lambda$22800/391684689.run(Unknown Source) ~[?:?] {}
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(SourceFile:1439) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.client.gui.screen.inventory.InventoryScreen.func_228187_a_(SourceFile:149) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at me.ichun.mods.morph.client.core.HudHandler.renderMorphEntity(HudHandler.java:1029) ~[?:10.1.0] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at me.ichun.mods.morph.client.core.HudHandler.drawSelector(HudHandler.java:719) ~[?:10.1.0] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at me.ichun.mods.morph.client.core.HudHandler.onIngameGuiPost(HudHandler.java:1328) ~[?:10.1.0] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.eventbus.ASMEventHandler_1203_HudHandler_onIngameGuiPost_Post.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3185/515186993.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.client.gui.ForgeIngameGui.post(ForgeIngameGui.java:818) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:morph.mixins.json:ForgeIngameGuiMixin,pl:mixin:A}
	at net.minecraftforge.client.gui.ForgeIngameGui.func_238445_a_(ForgeIngameGui.java:208) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:morph.mixins.json:ForgeIngameGuiMixin,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:765) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:astralsorcery:reach_set_client_renderer,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:astralsorcery:reach_set_client_renderer,pl:mixin:APP:aoa3.mixins.json:client.patch.GameRendererMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) [forge-1.16.5-36.2.35.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$505/1611714769.call(Unknown Source) [forge-1.16.5-36.2.35.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {re:classloading}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at vazkii.botania.client.core.handler.ContributorFancinessHandler.render(ContributorFancinessHandler.java:48) ~[?:1.16.5-420.2] {re:classloading}
	at vazkii.botania.client.core.handler.ContributorFancinessHandler.func_225628_a_(ContributorFancinessHandler.java:32) ~[?:1.16.5-420.2] {re:classloading}
	at net.minecraft.client.renderer.entity.LivingRenderer.func_225623_a_(LivingRenderer.java:204) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default,re:mixin,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.entity.PlayerRenderer.func_225623_a_(PlayerRenderer.java:64) ~[?:?] {re:mixin,xf:fml:forge:crossbows.2,pl:runtimedistcleaner:A,re:classloading,xf:fml:forge:crossbows.2,pl:mixin:APP:aoa3.mixins.json:client.patch.PlayerRendererMixin,pl:mixin:APP:morph.mixins.json:PlayerRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.PlayerRenderer.func_225623_a_(PlayerRenderer.java:41) ~[?:?] {re:mixin,xf:fml:forge:crossbows.2,pl:runtimedistcleaner:A,re:classloading,xf:fml:forge:crossbows.2,pl:mixin:APP:aoa3.mixins.json:client.patch.PlayerRendererMixin,pl:mixin:APP:morph.mixins.json:PlayerRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
-- Entity being rendered --
Details:
	Entity Type: minecraft:player (net.minecraft.client.entity.player.RemoteClientPlayerEntity)
	Entity ID: -70000000
	Entity Name: null
	Entity's Exact location: -15.50, 65.00, 176.50
	Entity's Block location: World: (-16,65,176), Chunk: (at 0,4,0 in -1,11; contains blocks -16,0,176 to -1,255,191), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.client.renderer.entity.PlayerRenderer@492c023b
	Location: 0.00,0.00,0.00 - World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: 0.0
	Delta: 1.0
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:311) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.gui.screen.inventory.InventoryScreen.func_241611_a_(SourceFile:149) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.gui.screen.inventory.InventoryScreen$$Lambda$22800/391684689.run(Unknown Source) ~[?:?] {}
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(SourceFile:1439) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.client.gui.screen.inventory.InventoryScreen.func_228187_a_(SourceFile:149) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at me.ichun.mods.morph.client.core.HudHandler.renderMorphEntity(HudHandler.java:1029) ~[?:10.1.0] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at me.ichun.mods.morph.client.core.HudHandler.drawSelector(HudHandler.java:719) ~[?:10.1.0] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at me.ichun.mods.morph.client.core.HudHandler.onIngameGuiPost(HudHandler.java:1328) ~[?:10.1.0] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.eventbus.ASMEventHandler_1203_HudHandler_onIngameGuiPost_Post.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3185/515186993.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.client.gui.ForgeIngameGui.post(ForgeIngameGui.java:818) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:morph.mixins.json:ForgeIngameGuiMixin,pl:mixin:A}
	at net.minecraftforge.client.gui.ForgeIngameGui.func_238445_a_(ForgeIngameGui.java:208) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:morph.mixins.json:ForgeIngameGuiMixin,pl:mixin:A}

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['LifeOrReality'/214, l='ClientLevel', x=3.33, y=64.00, z=183.04]]
	Chunk stats: Client Chunk Cache: 1521, 1155
	Level dimension: minecraft:overworld
	Level spawn location: World: (-16,64,176), Chunk: (at 0,4,0 in -1,11; contains blocks -16,0,176 to -1,255,191), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 3659 game time, 3659 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:mixin,xf:OptiFine:default,xf:fml:astralsorcery:sun_brightness_client,re:classloading,xf:OptiFine:default,xf:fml:astralsorcery:sun_brightness_client}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2031) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) [forge-1.16.5-36.2.35.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$505/1611714769.call(Unknown Source) [forge-1.16.5-36.2.35.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {re:classloading}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1938993104 bytes (1849 MB) / 5603590144 bytes (5344 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 12
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.35.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.35.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.35.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.35.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G8.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.35.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.35
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		BroomsMod-1.16.5-1.1.1.jar                        |Brooms                        |broomsmod                     |1.16.5-1.1.1        |DONE      |Manifest: NOSIGNATURE
		CyclopsCore-1.16.5-1.12.3.jar                     |Cyclops Core                  |cyclopscore                   |1.12.3              |DONE      |Manifest: NOSIGNATURE
		GokiStats-1.16.5-1.3.2.jar                        |Goki Stats                    |gokistats                     |1.3.2               |DONE      |Manifest: NOSIGNATURE
		astralsorcery-1.16-1.16.5-1.13.12.jar             |Astral Sorcery                |astralsorcery                 |1.16.5-1.13.12      |DONE      |Manifest: 45:2b:0a:49:6b:65:3b:39:a9:dd:d2:5b:55:7f:82:47:a5:1d:7a:cc:7f:a8:69:73:72:53:6f:57:4d:b2:1a:b7
		AdditionalEnchanting1.51.16.5.jar                 |Additional Enchanting         |additional_enchanting         |1.0.0               |DONE      |Manifest: NOSIGNATURE
		AoA3-1.16.5-3.6.4.jar                             |Advent of Ascension           |aoa3                          |1.16.5-3.6.4        |DONE      |Manifest: NOSIGNATURE
		Mine_and_Slash_BETA-1.16.5-4.0.18.jar             |Mine and Slash                |mmorpg                        |NONE                |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.152.jar                          |Just Enough Items             |jei                           |7.7.1.152           |DONE      |Manifest: NOSIGNATURE
		prefab-1.6.5.15.jar                               |Prefab                        |prefab                        |1.6.5.15            |DONE      |Manifest: NOSIGNATURE
		EverlastingAbilities-1.16.5-1.7.2.jar             |EverlastingAbilities          |everlastingabilities          |1.7.2               |DONE      |Manifest: NOSIGNATURE
		Mekanism-1.16.5-10.1.2.457.jar                    |Mekanism                      |mekanism                      |10.1.2              |DONE      |Manifest: NOSIGNATURE
		ForgeEndertech-1.16.5-7.2.2.0-build.0202.jar      |Forge Endertech               |forgeendertech                |7.2.2.0             |DONE      |Manifest: NOSIGNATURE
		journeymap-1.16.5-5.8.3.jar                       |Journeymap                    |journeymap                    |5.8.3               |DONE      |Manifest: NOSIGNATURE
		citadel-1.8.1-1.16.5.jar                          |Citadel                       |citadel                       |1.8.1               |DONE      |Manifest: NOSIGNATURE
		SimpleStorageNetwork-1.16.5-1.5.2.jar             |Simple Storage Network        |storagenetwork                |1.16.5-1.5.2        |DONE      |Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		u_team_core-1.16.5-3.2.1.208.jar                  |U Team Core                   |uteamcore                     |3.2.1.208           |DONE      |Manifest: f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		TinyMobFarm-1.16.3-1.1.1.jar                      |Tiny Mob Farm                 |tinymobfarm                   |1.1.1               |DONE      |Manifest: NOSIGNATURE
		iceandfire-2.1.9-1.16.5.jar                       |Ice and Fire                  |iceandfire                    |2.1.9-1.16.5        |DONE      |Manifest: NOSIGNATURE
		MekanismGenerators-1.16.5-10.1.2.457.jar          |Mekanism: Generators          |mekanismgenerators            |10.1.2              |DONE      |Manifest: NOSIGNATURE
		iChunUtil-1.16.5-10.5.1.jar                       |iChunUtil                     |ichunutil                     |10.5.1              |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.35-universal.jar                |Forge                         |forge                         |36.2.35             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		BloodMagic-1.16.4-3.1.8-28.jar                    |Blood Magic                   |bloodmagic                    |1.16.4-3.1.8-28     |DONE      |Manifest: NOSIGNATURE
		explorercraft-5.0.6.jar                           |Explorercraft                 |explorercraft                 |5.0.6               |DONE      |Manifest: NOSIGNATURE
		mx_lib_1.16.5_1.0.0.jar                           |MX_Lib                        |mx_lib                        |1.0.0               |DONE      |Manifest: NOSIGNATURE
		betterendforge-1.16.5-1.6.3.jar                   |BetterEnd Forge               |betterendforge                |1.16.5-1.6.3        |DONE      |Manifest: NOSIGNATURE
		Morph-1.16.5-10.1.0.jar                           |Morph                         |morph                         |10.1.0              |DONE      |Manifest: NOSIGNATURE
		ironchest-1.16.5-11.2.21.jar                      |Iron Chests                   |ironchest                     |1.16.5-11.2.21      |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.35-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		cofh_core-1.16.5-1.5.0.11.jar                     |CoFH Core                     |cofh_core                     |1.5.0.11            |DONE      |Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		ensorcellation-1.16.5-1.5.0.4.jar                 |Ensorcellation                |ensorcellation                |1.5.0.4             |DONE      |Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		TConstruct-1.16.5-3.3.3.332.jar                   |Tinkers' Construct            |tconstruct                    |3.3.3.332           |DONE      |Manifest: NOSIGNATURE
		sons-of-sins-1.16.5-1.0.9.jar                     |sons of sins                  |sons_of_sins                  |1.0.9               |DONE      |Manifest: NOSIGNATURE
		useful_backpacks-1.16.5-1.12.1.90.jar             |Useful Backpacks              |usefulbackpacks               |1.12.1.90           |DONE      |Manifest: f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		mana-and-artifice-1.5.1.7.jar                     |Mana and Artifice             |mana-and-artifice             |1.5.1.7             |DONE      |Manifest: NOSIGNATURE
		BiomesOPlenty-1.16.5-13.1.0.477-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.5-13.1.0.477   |DONE      |Manifest: NOSIGNATURE
		MekanismAdditions-1.16.5-10.1.2.457.jar           |Mekanism: Additions           |mekanismadditions             |10.1.2              |DONE      |Manifest: NOSIGNATURE
		baubles-1.8.7.1-1.16.5.jar                        |Baubles                       |baubles                       |1.8.7               |DONE      |Manifest: NOSIGNATURE
		rpgbackpacks-1.16.5-2.0.5.jar                     |RPG Backpacks                 |rpg_backpacks                 |2.0.5               |DONE      |Manifest: NOSIGNATURE
		AdLods-1.16.5-4.1.9.1-build.0206.jar              |Large Ore Deposits            |adlods                        |4.1.9.1             |DONE      |Manifest: NOSIGNATURE
		Botania-1.16.5-420.2.jar                          |Botania                       |botania                       |1.16.5-420.2        |DONE      |Manifest: NOSIGNATURE
		Divine_Missions-1.16.5-1.0.1.jar                  |Divine Missions               |divine_missions               |NONE                |DONE      |Manifest: NOSIGNATURE
		whisperwoods-1.16.5-2.0.2.jar                     |Whisperwoods                  |whisperwoods                  |2.0.2               |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.0.8.2.jar                   |Curios API                    |curios                        |1.16.5-4.0.8.2      |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.16.4-53.2.jar                         |Patchouli                     |patchouli                     |1.16.4-53.2         |DONE      |Manifest: NOSIGNATURE
		Mantle-1.16.5-1.6.157.jar                         |Mantle                        |mantle                        |1.6.157             |DONE      |Manifest: NOSIGNATURE
		xplosives-1.2.jar                                 |XPlosives                     |xplosives                     |1.2.0               |DONE      |Manifest: NOSIGNATURE
		World_of_Exile-1.16.5-1.4.3.jar                   |Dungeons of Exile             |world_of_exile                |NONE                |DONE      |Manifest: NOSIGNATURE
		structurize-1.16.5-1.0.392-RELEASE.jar            |Structurize                   |structurize                   |1.16.5-1.0.392-RELEA|DONE      |Manifest: NOSIGNATURE
		Library_of_Exile-1.16.5-1.2.3.jar                 |Library Of Exile              |library_of_exile              |NONE                |DONE      |Manifest: NOSIGNATURE
		minecolonies-1.16.5-1.0.736-RELEASE.jar           |MineColonies                  |minecolonies                  |1.16.5-1.0.736-RELEA|DONE      |Manifest: NOSIGNATURE
		MekanismTools-1.16.5-10.1.2.457.jar               |Mekanism: Tools               |mekanismtools                 |10.1.2              |DONE      |Manifest: NOSIGNATURE
		Vampirism-1.16.5-1.8.8.jar                        |Vampirism                     |vampirism                     |1.8.8               |DONE      |Manifest: NOSIGNATURE
		observerlib-1.16.5-1.5.3.jar                      |ObserverLib                   |observerlib                   |1.16.5-1.5.3        |DONE      |Manifest: NOSIGNATURE
		FastLeafDecay-v25.2.jar                           |FastLeafDecay                 |fastleafdecay                 |v25.2               |DONE      |Manifest: NOSIGNATURE
		DynamicTrees-1.16.5-0.10.0-Beta33.jar             |Dynamic Trees                 |dynamictrees                  |1.16.5-0.10.0-Beta33|DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.16.5-3.0.71.jar                  |GeckoLib                      |geckolib3                     |3.0.71              |DONE      |Manifest: NOSIGNATURE
		ars_nouveau-1.16.5-1.24.22.jar                    |Ars Nouveau                   |ars_nouveau                   |1.24.22             |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: b6624099-a3d5-49f7-b71a-1ef153a4f33c
	Patchouli open book context: n/a
	Launched Version: 1.16.5-forge-36.2.35
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) UHD Graphics 630 GL version 4.5.0 - Build 24.20.100.6345, Intel
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: Español (España)
	CPU: 12x Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
	OptiFine Version: OptiFine_1.16.5_HD_U_G8
	OptiFine Build: 20210515-161946
	Render Distance Chunks: 15
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 - Build 24.20.100.6345
	OpenGlRenderer: Intel(R) UHD Graphics 630
	OpenGlVendor: Intel
	CpuCount: 12

**Comment by W0tch3r** [comment]
Hello,
me and my friend are having the same issue. Its only crashing the client and not the Server.

**Comment by iChun** [comment]
You're crashing due to the player entity having a null name. This usually shouldn't happen unless (from what I suspect) you're playing offline/authentication servers are down/a cracked instance of Minecraft.

I've made it a lot less likely for this crash to happen for the next update, for the first two reasons I've stated. If you are playing a cracked instance of Minecraft, please try to support the game devs by purchasing the game legitimately.
