### ISSUE TITLE
Crash Morph with 1.16.5

### ISSUE THREAD

**Issue by misa7067** [iChun/Morph#1215]
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 05.06.22 2:44
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at de.budschie.bmorph.events.Events.onTargetBeingSet(Events.java:361) ~[?:1.16.5-3.0.1] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_77_Events_onTargetBeingSet_LivingSetAttackTargetEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3148/1695161087.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingSetAttackTarget(ForgeHooks.java:335) ~[?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:729) ~[?:?] {re:classloading}
	at net.minecraft.entity.MobEntity.func_70624_b(MobEntity.java:270) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at divinerpg.entities.base.EntityMageBase.func_70071_h_(EntityMageBase.java:48) ~[?:1.8.20] {re:classloading}
	at net.minecraft.client.world.ClientWorld.func_217418_a(ClientWorld.java:252) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.world.ClientWorld$$Lambda$10644/1739725835.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:hitbox,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:hitbox}
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:210) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1485) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:954) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.22.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$495/407241000.call(Unknown Source) [forge-1.16.5-36.2.22.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at de.budschie.bmorph.events.Events.onTargetBeingSet(Events.java:361) ~[?:1.16.5-3.0.1] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_77_Events_onTargetBeingSet_LivingSetAttackTargetEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3148/1695161087.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingSetAttackTarget(ForgeHooks.java:335) ~[?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:729) ~[?:?] {re:classloading}
	at net.minecraft.entity.MobEntity.func_70624_b(MobEntity.java:270) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at divinerpg.entities.base.EntityMageBase.func_70071_h_(EntityMageBase.java:48) ~[?:1.8.20] {re:classloading}
	at net.minecraft.client.world.ClientWorld.func_217418_a(ClientWorld.java:252) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.world.ClientWorld$$Lambda$10644/1739725835.accept(Unknown Source) ~[?:?] {}
-- Entity being ticked --
Details:
	Entity Type: divinerpg:spellbinder (divinerpg.entities.apalachia.EntitySpellbinder)
	Entity ID: 347041
	Entity Name: Spellbinder
	Entity's Exact location: -3684.31, 58.00, -7385.10
	Entity's Block location: World: (-3685,58,-7386), Chunk: (at 11,3,6 in -231,-462; contains blocks -3696,0,-7392 to -3681,255,-7377), Region: (-8,-15; contains chunks -256,-480 to -225,-449, blocks -4096,0,-7680 to -3585,255,-7169)
	Entity's Momentum: 0.00, -0.05, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:hitbox,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:hitbox}
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:210) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Jony_Bush'/321178, l='ClientLevel', x=-3687.81, y=58.39, z=-7375.76]]
	Chunk stats: Client Chunk Cache: 225, 43
	Level dimension: divinerpg:apalachia
	Level spawn location: World: (224,67,-16), Chunk: (at 0,4,0 in 14,-1; contains blocks 224,0,-16 to 239,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 10054900 game time, 1043 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2031) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.22.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$495/407241000.call(Unknown Source) [forge-1.16.5-36.2.22.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 500167448 bytes (476 MB) / 1474662400 bytes (1406 MB) up to 3526623232 bytes (3363 MB)
	CPUs: 3
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmn128M -Xmx3376M -XX:+UseConcMarkSweepGC
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.22.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.22.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.22.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.22.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine-OptiFine-1.16.5_HD_U_G8_pre2.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.22.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.22
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.22-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		Mendel_Vault_1.16.5_ru-en.jar                     |Mendel Vault                  |mendel_vault                  |1.4                 |DONE      |Manifest: NOSIGNATURE
		configured-1.5.2-1.16.5.jar                       |Configured                    |configured                    |1.5.2               |DONE      |Manifest: NOSIGNATURE
		repurposed_structures_forge-3.4.71.16.5.jar       |Repurposed Structures         |repurposed_structures         |3.4.7+1.16.5        |DONE      |Manifest: NOSIGNATURE
		bmorph-1.16.5-3.0.1.jar                           |Budschie's Morph Mod          |bmorph                        |1.16.5-3.0.1        |DONE      |Manifest: NOSIGNATURE
		Dungeons-Undead-1.16.5-v1.1.jar                   |Dungeons Undead               |dungeons_undead               |1.0.0               |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.152.jar                          |Just Enough Items             |jei                           |7.7.1.152           |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.22-universal.jar                |Forge                         |forge                         |36.2.22             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		CNB-1.16.3_5-1.2.11.jar                           |Creatures and Beasts          |cnb                           |1.2.11              |DONE      |Manifest: NOSIGNATURE
		BloodMagic-1.16.4-3.1.10-31.jar                   |Blood Magic                   |bloodmagic                    |1.16.4-3.1.10-31    |DONE      |Manifest: NOSIGNATURE
		twilightforest-1.16.5-4.0.870-universal(1).jar    |The Twilight Forest           |twilightforest                |NONE                |DONE      |Manifest: NOSIGNATURE
		tl_skin_cape_forge_1.16.5-1.19.jar                |TLSkinCape                    |tlskincape                    |1.19                |DONE      |Manifest: 19:f5:ce:44:81:0c:e4:22:05:5e:73:c5:a8:cd:de:f3:c8:cf:a9:b3:01:70:40:a0:ee:2d:50:7a:1c:3d:1c:8a
		supplementaries-1.16.5-0.18.4.jar                 |Supplementaries               |supplementaries               |0.18.2              |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.16.4-53.2.jar                         |Patchouli                     |patchouli                     |1.16.4-53.2         |DONE      |Manifest: NOSIGNATURE
		neat1.7-27.jar                                    |Neat                          |neat                          |1.7-27              |DONE      |Manifest: NOSIGNATURE
		Waystones_1.16.5-7.6.4.jar                        |Waystones                     |waystones                     |7.6.4               |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.16.5-3.0.16.jar                  |GeckoLib                      |geckolib3                     |3.0.16              |DONE      |Manifest: NOSIGNATURE
		DivineRPG-1.8.20-1.16.5.jar                       |DivineRPG                     |divinerpg                     |1.8.20              |DONE      |Manifest: NOSIGNATURE
		betterendforge-1.16.5-1.6.2.jar                   |BetterEnd Forge               |betterendforge                |1.16.5-1.6.2        |DONE      |Manifest: NOSIGNATURE
		selene-1.16.5-1.9.0.jar                           |Selene                        |selene                        |1.16.5-1.0          |DONE      |Manifest: NOSIGNATURE
		journeymap-1.16.5-5.8.5p2.jar                     |Journeymap                    |journeymap                    |5.8.5p2             |DONE      |Manifest: NOSIGNATURE
		ironchest-1.16.5-11.2.21(2).jar                   |Iron Chests                   |ironchest                     |1.16.5-11.2.21      |DONE      |Manifest: NOSIGNATURE
		citadel-1.8.0-1.16.5.jar                          |Citadel                       |citadel                       |1.8.0               |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.16.53-1.12.0.jar                      |Alex's Mobs                   |alexsmobs                     |1.12.0              |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: d71778d0-21ad-4301-9256-eea96c63f42e
	Patchouli open book context: n/a
	Launched Version: ForgeOptiFine 1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GT 630/PCIe/SSE2 GL version 4.6.0 NVIDIA 391.35, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: 
	Current Language: English (United Kingdom)
	CPU: 3x AMD Athlon(tm) II X3 460 Processor
	OptiFine Version: OptiFine_1.16.5_HD_U_G8_pre2
	OptiFine Build: 20210305-002749
	Render Distance Chunks: 4
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 391.35
	OpenGlRenderer: GeForce GT 630/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 3

**Comment by iChun** [comment]
That's not this morph mod.
