### ISSUE TITLE
Bug while going through nether portal

### ISSUE THREAD

**Issue by TinyDeskEngineer06** [iChun/Morph#1218]
I have experienced a bug where going through a nether portal while morphing will both crash the game, and put the player in a seemingly random place in the Nether upon reloading the world, nowhere near the portal they should've exited from. It can cause players to become stuck in terrain and also possibly drop them into an inescapable pool of lava. The coordinates the player is sent to do not seem to be similar to other notable coordinates, like 0, 0. The server crashes as soon as the dimension transition occurs.

**Comment by OpenSauce04** [comment]
Bump, I had this crash error too and produced a log
```
[11:48:27] [Client thread/ERROR]: Exception caught during firing event net.minecraftforge.client.event.RenderHandEvent@7b1c5e77:
java.lang.NullPointerException: null
	at net.minecraft.client.model.ModelBiped.setRotationAngles(SourceFile:123) ~[bpx.class:?]
	at net.minecraft.client.model.ModelPlayer.setRotationAngles(SourceFile:117) ~[bqj.class:?]
	at me.ichun.mods.morph.client.render.RenderPlayerHand.renderRightArm(RenderPlayerHand.java:106) ~[RenderPlayerHand.class:?]
	at net.minecraft.client.renderer.ItemRenderer.renderArmFirstPerson(ItemRenderer.java:255) ~[buu.class:?]
	at net.minecraft.client.renderer.ItemRenderer.renderItemInFirstPerson(ItemRenderer.java:358) ~[buu.class:?]
	at net.minecraft.client.renderer.ItemRenderer.renderItemInFirstPerson(ItemRenderer.java:333) ~[buu.class:?]
	at me.ichun.mods.morph.client.core.EventHandlerClient.onRenderHand(EventHandlerClient.java:797) ~[EventHandlerClient.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2461_EventHandlerClient_onRenderHand_RenderHandEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.client.ForgeHooksClient.renderFirstPersonHand(ForgeHooksClient.java:201) [ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.EntityRenderer.renderHand(EntityRenderer.java:772) [buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1439) [buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1259) [buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1062) [buq.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119) [bib.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:3942) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```
This appears to be an issue related to rendering the player's hand, likely due to the animation that plays while morphing being interrupted

**Comment by iChun** [comment]
> I have experienced a bug where going through a nether portal while morphing will both crash the game, and put the player in a seemingly random place in the Nether upon reloading the world, nowhere near the portal they should've exited from. It can cause players to become stuck in terrain and also possibly drop them into an inescapable pool of lava. The coordinates the player is sent to do not seem to be similar to other notable coordinates, like 0, 0. The server crashes as soon as the dimension transition occurs.

Sorry bout the late reply but I will need a crash log to debug this. 

@OpenSauce04 Your crash seems related to a version of Morph I no longer support. I only provide support for Morph 1.16.5 and later now.
