### ISSUE TITLE
My server sometimes can´t keep up and this is error one guy from curseforge support found

### ISSUE THREAD

**Issue by iceyy0044** [iChun/Morph#1234]
[10:46:42] [Server thread/INFO] [STDERR]: [me.ichun.mods.morph.common.Morph:onIMCMessage:148]: java.lang.ClassNotFoundException: com.animania.common.entities.cows.EntityAnimaniaCow
[10:46:42] [Server thread/INFO] [STDERR]: [me.ichun.mods.morph.common.Morph:onIMCMessage:148]:     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
[10:46:42] [Server thread/INFO] [STDERR]: [me.ichun.mods.morph.common.Morph:onIMCMessage:148]:     at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
[10:46:42] [Server thread/INFO] [STDERR]: [me.ichun.mods.morph.common.Morph:onIMCMessage:148]:     at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
[10:46:42] [Server thread/INFO] [STDERR]: [me.ichun.mods.morph.common.Morph:onIMCMessage:148]:     at java.lang.Class.forName0(Native Method)
[10:46:42] [Server thread/INFO] [STDERR]: [me.ichun.mods.morph.common.Morph:onIMCMessage:148]:     at java.lang.Class.forName(Class.java:264)
[10:46:42] [Server thread/INFO] [STDERR]: [me.ichun.mods.morph.common.Morph:onIMCMessage:148]:     at me.ichun.mods.morph.common.Morph.onIMCMessage(Morph.java:132)
[10:46:42] [Server thread/INFO] [STDERR]: [me.ichun.mods.morph.common.Morph:onIMCMessage:148]:     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:46:42] [Server thread/INFO] [STDERR]: [me.ichun.mods.morph.common.Morph:onIMCMessage:148]:     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

**Comment by iceyy0044** [comment]
PS : It is 1.12.2 version

**Comment by iChun** [comment]
https://github.com/iChun/Morph/issues/878
