### ISSUE TITLE
Clear command not working

### ISSUE THREAD

**Issue by RenKyoKrishna** [iChun/Morph#760]
Whenever I use the morph clear command, I get an "unknown error" I've been trying to solve this forever. Can anyone help? I can't seem to find a fix for this anywhere. Here's the error.

[05:19:42] [Server thread/ERROR]: Couldn't process command: 'morph clear'
java.lang.ArrayIndexOutOfBoundsException: 1
at morph.common.core.CommandMorph.func_71515_b(CommandMorph.java:166) ~[CommandMorph.class:?]
at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739) [nh.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718) [nh.class:?]
at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ir.class:?]
at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ir.class:?]
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[05:19:42] [Client thread/INFO]: [CHAT] An unknown error occurred while attempting to perform this command

**Comment by iChun** [comment]
Bit late on this, but you're supposed to mention which user's morphs list you want to clear as well.

**Comment by RenKyoKrishna** [comment]
When I use the name, it says "Player's morphs cleared" and demorphs the player if they are in morph, but their morphs aren't really cleared.

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
