### ISSUE TITLE
Crash when transforming

### ISSUE THREAD

**Issue by downnboutdat** [iChun/Morph#765]
Crash when attempting to transform (only sometimes). I am playing this mod v0.9.2 as part of the cloud 9 mod-pack v1.2.0. When I transform, sometimes clients crash to desktop. It's not always the person who transformed who crashes. Some examples: Sometimes player A transforms and nobody crashes. Sometimes Player A transforms and Players A, B, C, and D crash. Sometimes Player B transforms and player B crashes. Sometimes Player B transforms and players A and C crash. I included a crash log from one of the players.

[18:06:18] [Client thread/ERROR] [FML/]: Exception caught during firing event cpw.mods.fml.common.gameevent.TickEvent$PlayerTickEvent@376d98aa:
java.lang.ClassCastException: net.minecraft.client.entity.EntityOtherPlayerMP cannot be cast to net.minecraft.client.entity.EntityPlayerSP
	at team.chisel.block.BlockConcrete.speedupPlayer(BlockConcrete.java:34) ~[BlockConcrete.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_214_BlockConcrete_speedupPlayer_PlayerTickEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:345) [FMLCommonHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:220) [yz.class:?]
	at net.minecraft.client.entity.EntityOtherPlayerMP.func_70071_h_(EntityOtherPlayerMP.java:59) [bll.class:?]
	at morph.client.core.TickHandlerClient.worldTick(TickHandlerClient.java:851) [TickHandlerClient.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_601_TickHandlerClient_worldTick_ClientTickEvent.invoke(.dynamic) [?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:330) [FMLCommonHandler.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2064) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_65]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_65]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
[18:06:18] [Client thread/ERROR] [FML/]: Index: 22 Listeners:
[18:06:18] [Client thread/ERROR] [FML/]: 0: NORMAL
[18:06:18] [Client thread/ERROR] [FML/]: 1: ASM: net.nevermine.event.equipment.ArmorEffects@6c5f8a23 onTickEvent(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 2: ASM: net.nevermine.event.resource.CalefactionTicker@1b14d518 onTickEvent(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 3: ASM: net.nevermine.event.resource.CalefactionTicker@1b14d518 onTickingEvent(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 4: ASM: net.nevermine.event.equipment.SniperEvent@42206830 onTickEvent(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 5: ASM: net.nevermine.event.equipment.HoldItemEvent@67c65978 onTickEvent(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 6: ASM: net.nevermine.event.equipment.HelmetEvent@6defb594 onTickEvent(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 7: ASM: net.nevermine.event.equipment.ArtistryRequirement@24b64f02 onTickEvent(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 8: ASM: net.nevermine.event.dimensional.GardencianOceanEvent@ccc7ef onTickEvent(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 9: ASM: net.nevermine.event.dimensional.CandylandStickyEvent@66cdc806 onTickEvent(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 10: ASM: net.nevermine.event.dimensional.CavernAmbientEvent@5bdc7fa1 onTickEvent(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 11: ASM: net.nevermine.event.dimensional.LelyetianUnder@5ccd7f1b onTickEvent(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 12: ASM: net.nevermine.event.resource.TributeTicker@69942950 onTickEvent(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 13: ASM: net.nevermine.event.resource.ExpeditionEvent@51226e45 windyLegsEvent(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 14: ASM: net.nevermine.event.resource.ExpeditionEvent@51226e45 onTickEvent(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 15: ASM: net.nevermine.resource.energy.energyTickHandler@78546589 onTick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 16: ASM: net.nevermine.resource.creation.creationTickHandler@5a79668b onTick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 17: ASM: net.nevermine.resource.soulpower.soulPowerTickHandler@5f0c90f2 onTick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 18: ASM: net.nevermine.resource.calefaction.calefactionTickHandler@59d944a9 onTick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 19: ASM: net.nevermine.resource.boss.bossBarTickHandler@766d60e4 onTick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 20: ASM: mods.railcraft.common.blocks.hidden.TrailTicker@7d2ed tick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 21: ASM: mods.railcraft.common.items.firestone.FirestoneTickHandler@7e8e70d5 tick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 22: ASM: team.chisel.block.BlockConcrete@667dd4ee speedupPlayer(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 23: ASM: com.rwtema.extrautils.crafting.LawSwordCraftHandler@6beec2e6 event(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 24: ASM: tconstruct.armor.ArmorAbilities@300e8833 playerTick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 25: ASM: us.ichun.mods.ichunutil.common.core.TickHandlerServer@d067ba1 playerTick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 26: ASM: ichun.client.voxel.TrailTicker@5897e76c playerTick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 27: ASM: codechicken.nei.ServerHandler@55fcd93 tickEvent(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 28: ASM: baubles.common.event.KeyHandler@90743c3 playerTick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 29: ASM: mods.railcraft.common.plugins.forestry.IceManTickHandler@53f52c0f tick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 30: ASM: powercrystals.minefactoryreloaded.MineFactoryReloadedClient@342ad7e0 tickStart(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 31: ASM: morph.common.core.TickHandlerServer@6041b532 playerTick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 32: ASM: openblocks.common.ServerTickHandler@2a8b24a6 onPlayerTick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 33: ASM: mcjty.rftools.FMLEventHandlers@16b33d6b onPlayerTickEvent(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 34: ASM: tterrag.core.common.handlers.FireworkHandler@1d8f4a03 onPlayerTick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 35: ASM: forestry.core.TickHandlerCoreClient@6073f4fb onPlayerTick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 36: ASM: com.rwtema.extrautils.worldgen.Underdark.DarknessTickHandler@39bdf2ef tickStart(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 37: ASM: vazkii.botania.common.block.BlockPistonRelay@44bb5da2 tickEnd(Lcpw/mods/fml/common/gameevent/TickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 38: LOWEST
[18:06:18] [Client thread/ERROR] [FML/]: 39: ASM: vazkii.botania.common.item.ItemRegenIvy@494132d0 onTick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: Exception caught during firing event cpw.mods.fml.common.gameevent.TickEvent$ClientTickEvent@40e51c74:
java.lang.ClassCastException: net.minecraft.client.entity.EntityOtherPlayerMP cannot be cast to net.minecraft.client.entity.EntityPlayerSP
	at team.chisel.block.BlockConcrete.speedupPlayer(BlockConcrete.java:34) ~[BlockConcrete.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_214_BlockConcrete_speedupPlayer_PlayerTickEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:345) ~[FMLCommonHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:220) ~[yz.class:?]
	at net.minecraft.client.entity.EntityOtherPlayerMP.func_70071_h_(EntityOtherPlayerMP.java:59) ~[bll.class:?]
	at morph.client.core.TickHandlerClient.worldTick(TickHandlerClient.java:851) ~[TickHandlerClient.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_601_TickHandlerClient_worldTick_ClientTickEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:330) [FMLCommonHandler.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2064) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_65]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_65]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
[18:06:18] [Client thread/ERROR] [FML/]: Index: 20 Listeners:
[18:06:18] [Client thread/ERROR] [FML/]: 0: NORMAL
[18:06:18] [Client thread/ERROR] [FML/]: 1: ASM: net.nevermine.event.player.ClientTicker@7cdab2a8 tickClient(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 2: ASM: mods.railcraft.client.sounds.SoundLimiterTicker@42fa2227 tick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 3: ASM: codechicken.enderstorage.storage.liquid.TankSynchroniser@2e5cdb5f tickEnd(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 4: ASM: ichun.client.core.TickHandlerClient@5535f1cb clientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 5: ASM: ichun.client.voxel.TrailTicker@5897e76c worldTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 6: ASM: aroma1997.core.client.events.ClientEventListener@1b00eb74 tick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 7: ASM: codechicken.core.internal.CCCEventHandler@11d3fd28 clientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 8: ASM: codechicken.nei.ClientHandler@52b7754 tickEvent(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 9: ASM: squeek.applecore.client.HUDOverlayHandler@7e20358e onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 10: ASM: vazkii.botania.common.core.handler.CommonTickHandler@7fc64b9e onTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 11: ASM: vazkii.botania.client.core.handler.ClientTickHandler@7629cc4c clientTickEnd(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 12: ASM: vazkii.botania.client.core.handler.CorporeaAutoCompleteHandler@2c39d59b onTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 13: ASM: mods.railcraft.common.util.misc.BlinkTick@6acb4f62 tick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 14: ASM: build.EventHandlerFML@77e9cee1 tickClient(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 15: ASM: INSTANCE onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 16: ASM: com.rwtema.extrautils.EventHandlerClient@349b78d9 getTimer(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 17: ASM: com.rwtema.extrautils.item.RenderItemGlove@3e032a6c tickCol(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 18: ASM: mcp.mobius.waila.overlay.WailaTickHandler@6681f99d tickClient(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 19: ASM: invtweaks.forge.ForgeClientTick@585728aa onTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 20: ASM: morph.client.core.TickHandlerClient@46310b03 worldTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 21: ASM: openblocks.client.ClientTickHandler@292d628b onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 22: ASM: tonius.simplyjetpacks.client.handler.ClientTickHandler@6d73e913 onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 23: ASM: tonius.simplyjetpacks.client.handler.KeyHandler@21e3ba9e onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 24: ASM: codechicken.translocator.CraftingGridKeyHandler@8fc56a0 tick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 25: ASM: net.tropicraft.event.TCMiscEvents@72adf6a3 tickClient(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 26: ASM: tterrag.core.client.handlers.ClientHandler@b1eba5f onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 27: ASM: tterrag.core.common.util.Scheduler@3b09d25b onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 28: ASM: cofh.core.render.ShaderHelper@206f5871 clientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 29: ASM: mods.railcraft.client.core.LatestVersionMessage@6fc06a1b tick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 30: ASM: mods.railcraft.client.core.LocomotiveKeyHandler@21a58c4 tick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 31: ASM: mods.railcraft.client.core.DebugViewTicker@37bbb950 tick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 32: ASM: codechicken.lib.world.WorldExtensionManager$WorldExtensionEventHandler@24113fb9 clientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 33: ASM: codechicken.multipart.ControlKeyHandler$@61e5e3ca tick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 34: ASM: tconstruct.armor.ArmorTickHandler@3c643210 tickEnd(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 35: ASM: net.techbrew.journeymap.forge.event.StateTickHandler@493a66d onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 36: ASM: mrtjp.core.render.RenderTicker$@618e24fc clientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 37: ASM: mrtjp.projectred.core.libmc.fx.ParticleManagement@2dfd7cd8 tickEnd(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 38: ASM: mrtjp.core.fx.FXEngine$@1883d15e tickEnd(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 39: ASM: mrtjp.projectred.expansion.SpacebarClientTracker$@10c6eb6a tick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 40: ASM: mrtjp.projectred.expansion.ForwardClientTracker$@27f70803 tick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 41: ASM: mrtjp.projectred.expansion.ItemJetpack$@4315315a onRenderTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 42: ASM: cofh.thermaldynamics.core.TickHandlerClient@53a7f163 tick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 43: ASM: cofh.thermaldynamics.render.RenderDuctItems@6a27f2a2 clientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 44: ASM: mrtjp.relocation.RelocationClientEventHandler$@2e43ea9c clientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[18:06:18] [Client thread/ERROR] [FML/]: 45: ASM: vazkii.botania.common.block.BlockPistonRelay@44bb5da2 tickEnd(Lcpw/mods/fml/common/gameevent/TickEvent;)V
[18:06:20] [Client thread/INFO] [journeymap/]: Mapping halted in D:\Minecraft\FTB\FTBPresentsCloud9\minecraft\journeymap\data\mp\Cotton~Candy_77c9e79f~5dfa~40dd~9e37~bbdfb487b581\DIM0
[18:06:20] [Client thread/DEBUG] [FML/]: Reverting to frozen data state.
[18:06:20] [Client thread/INFO] [FML/]: Applying holder lookups
[18:06:20] [Client thread/WARN] [FML/]: Unable to lookup chisel:cobblestoneWall for public static team.chisel.block.BlockCarvableWall team.chisel.init.ChiselBlocks.cobblestoneWall. Is there something wrong with the registry?
[18:06:20] [Client thread/WARN] [FML/]: Unable to lookup chisel:obsidian2 for public static team.chisel.block.BlockCarvable team.chisel.init.ChiselBlocks.obsidian2. Is there something wrong with the registry?
[18:06:20] [Client thread/WARN] [FML/]: Unable to lookup chisel:voidstonerunic for public static team.chisel.block.BlockCarvable team.chisel.init.ChiselBlocks.voidstonerunic. Is there something wrong with the registry?
[18:06:20] [Client thread/WARN] [FML/]: Unable to lookup chisel:circuits for public static team.chisel.block.BlockCarvable team.chisel.init.ChiselBlocks.circuits. Is there something wrong with the registry?
[18:06:20] [Client thread/WARN] [FML/]: Unable to lookup chisel:arcane for public static team.chisel.block.BlockCarvable team.chisel.init.ChiselBlocks.arcane. Is there something wrong with the registry?
[18:06:20] [Client thread/WARN] [FML/]: Unable to lookup chisel:thaumium for public static team.chisel.block.BlockCarvable team.chisel.init.ChiselBlocks.thaumium. Is there something wrong with the registry?
[18:06:20] [Client thread/WARN] [FML/]: Unable to lookup chisel:tallow for public static team.chisel.block.BlockCarvable team.chisel.init.ChiselBlocks.tallow. Is there something wrong with the registry?
[18:06:20] [Client thread/WARN] [FML/]: Unable to lookup chisel:bloodRune for public static team.chisel.block.BlockCarvable team.chisel.init.ChiselBlocks.bloodRune. Is there something wrong with the registry?
[18:06:20] [Client thread/WARN] [FML/]: Unable to lookup chisel:bloodBrick for public static team.chisel.block.BlockCarvable team.chisel.init.ChiselBlocks.bloodBrick. Is there something wrong with the registry?
[18:06:20] [Client thread/INFO] [FML/]: Holder lookups applied
[18:06:23] [Client thread/INFO] [STDOUT/]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 10/27/15 6:06 PM
Description: Unexpected error

java.lang.ClassCastException: net.minecraft.client.entity.EntityOtherPlayerMP cannot be cast to net.minecraft.client.entity.EntityPlayerSP
	at team.chisel.block.BlockConcrete.speedupPlayer(BlockConcrete.java:34)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_214_BlockConcrete_speedupPlayer_PlayerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:345)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:220)
	at net.minecraft.client.entity.EntityOtherPlayerMP.func_70071_h_(EntityOtherPlayerMP.java:59)
	at morph.client.core.TickHandlerClient.worldTick(TickHandlerClient.java:851)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_601_TickHandlerClient_worldTick_ClientTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:330)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2064)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by iChun** [comment]
Please report it to the chisel team, this is their crash

**Comment by downnboutdat** [comment]
Ahh- thanks. Sorry I'm not very good at reading java errors. Looks like a big mess to me
