### ISSUE TITLE
Crashes on loading world

### ISSUE THREAD

**Issue by vaindil** [iChun/Morph#779]
Hello! I'm trying to install this for my brother, I'm a developer but know nothing about Minecraft. He's using 1.7.10 with Forge, Morph 0.9.2, and iChunUtil 4.2.2. These two are the only mods he has, I tried to install them for him tonight. The game crashes when loading a world or creating a new one (local only, single player). The crash report is below. I tried on Java 8u66 and 7u80, same report on both.

    ---- Minecraft Crash Report ----
    // You should try our sister game, Minceraft!
    
    Time: 12/8/15 9:23 PM
    Description: Unexpected error
    
    java.lang.IndexOutOfBoundsException: 18496
    	at java.nio.DirectIntBufferU.get(Unknown Source)
    	at net.minecraft.client.renderer.RenderGlobal.func_72712_a(RenderGlobal.java:350)
    	at net.minecraft.client.renderer.RenderGlobal.func_72732_a(RenderGlobal.java:294)
    	at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2216)
    	at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2146)
    	at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:240)
    	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:70)
    	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:13)
    	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2061)
    	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    	at net.minecraft.client.main.Main.main(SourceFile:148)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    	at java.lang.reflect.Method.invoke(Unknown Source)
    	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    
    
    A detailed walkthrough of the error, its code path and all known details is as follows:
    ---------------------------------------------------------------------------------------
    
    -- Head --
    Stacktrace:
    	at java.nio.DirectIntBufferU.get(Unknown Source)
    	at net.minecraft.client.renderer.RenderGlobal.func_72712_a(RenderGlobal.java:350)
    	at net.minecraft.client.renderer.RenderGlobal.func_72732_a(RenderGlobal.java:294)
    	at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2216)
    	at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2146)
    	at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:240)
    	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:70)
    	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:13)
    	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    
    -- Affected level --
    Details:
    	Level name: MpServer
    	All players: 0 total; []
    	Chunk stats: MultiplayerChunkCache: 0, 0
    	Level seed: 0
    	Level generator: ID 01 - flat, ver 0. Features enabled: false
    	Level generator options: 
    	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    	Level time: 0 game time, 0 day time
    	Level dimension: 0
    	Level storage version: 0x00000 - Unknown?
    	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    	Forced entities: 0 total; []
    	Retry entities: 0 total; []
    	Server brand: ~~ERROR~~ NullPointerException: null
    	Server type: Integrated singleplayer server
    Stacktrace:
    	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
    	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
    	at net.minecraft.client.main.Main.main(SourceFile:148)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    	at java.lang.reflect.Method.invoke(Unknown Source)
    	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    
    -- System Details --
    Details:
    	Minecraft Version: 1.7.10
    	Operating System: Windows 10 (x86) version 10.0
    	Java Version: 1.8.0_66, Oracle Corporation
    	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    	Memory: 63170472 bytes (60 MB) / 292626432 bytes (279 MB) up to 523501568 bytes (499 MB)
    	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 5 mods loaded, 5 mods active
    	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
    	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
    	UCHIJAAAA	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
    	UCHIJAAAA	iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2.jar) 
    	UCHIJAAAA	Morph{0.9.2} [Morph] (Morph-Beta-0.9.2.jar) 
    	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.201.1151.0' Renderer: 'AMD Radeon HD 5450'
    	Launched Version: 1.7.10-Forge10.13.4.1558-1.7.10
    	LWJGL: 2.9.1
    	OpenGL: AMD Radeon HD 5450 GL version 4.5.13399 Compatibility Profile Context 15.201.1151.0, ATI Technologies Inc.
    	GL Caps: Using GL 1.3 multitexturing.
    Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
    Anisotropic filtering is supported and maximum anisotropy is 16.
    Shaders are available because OpenGL 2.1 is supported.
    
    	Is Modded: Definitely; Client brand changed to 'fml,forge'
    	Type: Client (map_client.txt)
    	Resource Packs: []
    	Current Language: English (UK)
    	Profiler Position: N/A (disabled)
    	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    	Anisotropic Filtering: Off (1)

**Comment by iChun** [comment]
Does Minecraft run with just Forge installed?

**Comment by iChun** [comment]
Also make sure your drivers are updated. Especially if you have more than
one video card

**Comment by iChun** [comment]
No response for ~2 months, closing.
