### ISSUE TITLE
My game crashes when I open the morph menu plz help :(

### ISSUE THREAD

**Issue by zen3218** [iChun/Morph#790]
here the crash report:
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 24/01/16 10:36 AM
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
	at Zyldra.CC2.client.Render.Special.RenderWings.doRender(RenderWings.java:35)
	at Zyldra.CC2.Event.EventCC2.handleRenderLivingEvent(EventCC2.java:261)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_44_EventCC2_handleRenderLivingEvent_Post.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraft.client.renderer.entity.RendererLivingEntity.func_76986_a(RendererLivingEntity.java:281)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:158)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:521)
	at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:293)
	at net.minecraft.client.renderer.entity.RenderManager.func_147940_a(RenderManager.java:276)
	at morph.client.core.TickHandlerClient.drawEntityOnScreen(TickHandlerClient.java:1014)
	at morph.client.core.TickHandlerClient.renderTick(TickHandlerClient.java:365)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_224_TickHandlerClient_renderTick_RenderTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onRenderTickEnd(FMLCommonHandler.java:340)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1003)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at Zyldra.CC2.client.Render.Special.RenderWings.doRender(RenderWings.java:35)
	at Zyldra.CC2.Event.EventCC2.handleRenderLivingEvent(EventCC2.java:261)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_44_EventCC2_handleRenderLivingEvent_Post.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraft.client.renderer.entity.RendererLivingEntity.func_76986_a(RendererLivingEntity.java:281)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:158)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:521)

-- Entity being rendered --
Details:
	Entity Type: null (net.minecraft.client.entity.EntityOtherPlayerMP)
	Entity ID: 296
	Entity Name: swegslime3218
	Entity's Exact location: 192.50, 66.62, 256.50
	Entity's Block location: World: (192,66,256), Chunk: (at 0,4,0 in 12,16; contains blocks 192,0,256 to 207,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.client.renderer.entity.RenderPlayer@13955416
	Location: 0.00,0.00,0.00 - World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: 0.0
	Delta: 1.0
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:293)
	at net.minecraft.client.renderer.entity.RenderManager.func_147940_a(RenderManager.java:276)
	at morph.client.core.TickHandlerClient.drawEntityOnScreen(TickHandlerClient.java:1014)
	at morph.client.core.TickHandlerClient.renderTick(TickHandlerClient.java:365)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_224_TickHandlerClient_renderTick_RenderTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['zen3218'/274, l='MpServer', x=-40.25, y=70.62, z=324.78]]
	Chunk stats: MultiplayerChunkCache: 32, 41
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (192,64,256), Chunk: (at 0,4,0 in 12,16; contains blocks 192,0,256 to 207,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 198038 game time, 198038 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 28 total; [EntityBat['Bat'/1216, l='MpServer', x=-61.05, y=15.29, z=321.40], EntityBat['Bat'/1218, l='MpServer', x=-65.25, y=11.01, z=312.33], EntityChicken['Chicken'/1155, l='MpServer', x=-48.50, y=67.00, z=319.50], EntityBat['Bat'/1219, l='MpServer', x=-69.01, y=12.49, z=315.56], EntityChicken['Chicken'/1156, l='MpServer', x=-48.50, y=67.00, z=319.50], EntityCow['Cow'/1157, l='MpServer', x=-63.50, y=71.00, z=304.50], EntityChicken['Chicken'/1158, l='MpServer', x=-56.50, y=71.00, z=307.50], EntityChicken['Chicken'/1159, l='MpServer', x=-58.50, y=72.00, z=305.50], EntityChicken['Chicken'/1160, l='MpServer', x=-57.50, y=70.00, z=309.50], EntityChicken['Chicken'/1161, l='MpServer', x=-60.50, y=72.00, z=305.50], EntityChicken['Chicken'/1103, l='MpServer', x=-19.50, y=67.00, z=326.50], EntityChicken['Chicken'/1104, l='MpServer', x=-23.47, y=67.00, z=327.47], EntityChicken['Chicken'/1168, l='MpServer', x=-70.50, y=72.00, z=307.50], EntityChicken['Chicken'/1105, l='MpServer', x=-24.56, y=70.00, z=329.53], EntityChicken['Chicken'/1169, l='MpServer', x=-68.50, y=71.00, z=305.50], EntityChicken['Chicken'/1170, l='MpServer', x=-66.50, y=71.00, z=306.50], EntityClientPlayerMP['zen3218'/274, l='MpServer', x=-40.25, y=70.62, z=324.78], EntityCow['Cow'/1171, l='MpServer', x=-65.50, y=71.00, z=304.50], EntityTrail['unknown'/276, l='MpServer', x=-40.25, y=70.62, z=324.78], EntityItem['item.tile.sapling.oak'/1185, l='MpServer', x=8.31, y=75.13, z=280.06], EntityBat['Bat'/1122, l='MpServer', x=1.13, y=24.00, z=285.53], EntityItem['item.item.apple'/1186, l='MpServer', x=13.78, y=81.13, z=280.44], EntityChicken['Chicken'/1130, l='MpServer', x=-45.50, y=64.00, z=324.50], EntityChicken['Chicken'/1131, l='MpServer', x=-47.50, y=65.00, z=320.50], EntityChicken['Chicken'/1132, l='MpServer', x=-35.50, y=79.00, z=274.50], EntityChicken['Chicken'/1133, l='MpServer', x=-33.50, y=80.00, z=273.50], EntityChicken['Chicken'/1134, l='MpServer', x=-33.50, y=80.00, z=274.50], EntityChicken['Chicken'/1135, l='MpServer', x=-36.91, y=81.00, z=279.53]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 3.13.0-63-generic
	Java Version: 1.8.0_66, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 230451448 bytes (219 MB) / 588689408 bytes (561 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 Optifine OptiFine_1.7.10_HD_C1 23 mods loaded, 23 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
	UCHIJAAAA	lucky{5.1.0} [Lucky Block] ([1-7-10]_Lucky_Block_v5-1-0.jar) 
	UCHIJAAAA	divinerpg{1.4.1.3} [DivineRPG] ([1.7.10][SMP]DivineRPG-1.4.1.3.jar) 
	UCHIJAAAA	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	UCHIJAAAA	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
	UCHIJAAAA	CC2{2.55} [ChaosCraft] (Chaoscraft 1.7.10-2.55.jar) 
	UCHIJAAAA	ComputerCraft{1.75} [ComputerCraft] (ComputerCraft1.75.jar) 
	UCHIJAAAA	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
	UCHIJAAAA	iChunUtil{4.0.0} [iChunUtil] (iChun-Util-Mod-1.7.10.jar) 
	UCHIJAAAA	InventoryPets{1.3.5} [Inventory Pets] (inventorypets-1.7.10-1.3.5.jar) 
	UCHIJAAAA	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
	UCHIJAAAA	mm{1.0} [Minecraft Money] (MinecraftMoney-1.7.10-1.0.jar) 
	UCHIJAAAA	Morph{0.9.2} [Morph] (Morph-Beta-0.9.2.jar) 
	UCHIJAAAA	cfm{3.4.7} [�9MrCrayfish's Furniture Mod] (MrCrayfishs-Furniture-Mod-1.7.10(1).jar) 
	UCHIJAAAA	ReiMinimap{1.7.10} [Rei's Minimap] (Reis-Minimap-Mod-1.7.10(1).jar) 
	UCHIJAAAA	SoMuchArmor{Alpha 2.1} [So Much Armor] (So Much Armor-1.7.10-2.3.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.7.build979} [Tinkers' Construct] (TConstruct-1.7.10-1.8.7.jar) 
	UCHIJAAAA	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
	GL info: ' Vendor: 'X.Org R300 Project' Version: '2.1 Mesa 10.1.3' Renderer: 'Gallium 0.4 on ATI RS480'
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	TConstruct Environment: Environment healthy.
	Launched Version: 1.7.10-Forge10.13.4.1448-1.7.10
	LWJGL: 2.9.1
	OpenGL: Gallium 0.4 on ATI RS480 GL version 2.1 Mesa 10.1.3, X.Org R300 Project
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by zen3218** [comment]
By the way I play this with my brother on a LAN world and it is my world. I crash every time when I open the menu to morph when I tried to play by myself

**Comment by Tamaized** [comment]
CC2, which looks like ChaosCraft, is the cause. Send the report to that mod author.

**Comment by iChun** [comment]
Yeah please inform the author of ChaosCraft if they could do something about it.
