### ISSUE TITLE
Crashed when finished loading

### ISSUE THREAD

**Issue by Hans5958** [iChun/Morph#794]
Crashed when the forge is finished loading, HALP?!!

Have saw the https://github.com/iChun/Morph/issues/732, I didn't unpack the jars.

Thanks!

Minecraft 1.7.10. Updating Java right now...
---- Minecraft Crash Report ----
// Don't do that.

Time: 29/01/16 16:43
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.IllegalAccessError: tried to access field net.minecraft.client.renderer.entity.RendererLivingEntity.field_77045_g from class morph.client.core.ClientProxy
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:744)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalAccessError: tried to access field net.minecraft.client.renderer.entity.RendererLivingEntity.field_77045_g from class morph.client.core.ClientProxy
    at morph.client.core.ClientProxy.initPostMod(ClientProxy.java:93)
    at morph.common.Morph.postLoad(Morph.java:189)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
    ... 10 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (x86) version 6.1
    Java Version: 1.8.0_60, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 240198456 bytes (229 MB) / 515629056 bytes (491 MB) up to 523501568 bytes (499 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 Optifine OptiFine_1.7.10_HD_U_C1 66 mods loaded, 66 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJ   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJ   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1558-1.7.10.jar) 
    UCHIJ   Forge{10.13.4.1558} [Minecraft Forge](forge-1.7.10-10.13.4.1558-1.7.10.jar) 
    UCHIJ   itemphysic{0.8.3} [ItemPhysic](minecraft.jar) 
    UCHIJ   AIRI{3.1.0.175} [AIRI]([1.7.10-10.13.4.1558-1.7.10][3.1.0.175] AIRI.zip) 
    UCHIJ   avp{4.0.0.371} [AliensVsPredator]([1.7.10-10.13.4.1558-1.7.10][4.0.0.371] AliensVsPredator.zip) 
    UCHIJ   furnace3d{1.4.0} [Furnace 3D]([1.7.10] 3D Furnace-1.4.jar) 
    UCHIJ   mopickaxes{630} [Mo' Pickaxes]([1.7.10] CST7 Mo' Pickaxes 630.jar) 
    UCHIJ   Amberoguia{1.5.4} [Amberoguia]([1.7.10]AmberoguiaMod_v1.5.4.jar) 
    UCHIJ   bspkrsCore{6.16} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.16.zip) 
    UCHIJ   ArmorStatusHUD{1.28} [ArmorStatusHUD]([1.7.10]ArmorStatusHUD-client-1.28.zip) 
    UCHIJ   DamageIndicatorsMod{3.2.3} [Damage Indicators]([1.7.10]DamageIndicatorsMod-3.2.3.jar) 
    UCHIJ   DirectionHUD{1.24} [DirectionHUD]([1.7.10]DirectionHUD-client-1.24.zip) 
    UCHIJ   imsm{1.7.10} [Instant Massive Structures Mod]([1.7.10]InstantMassiveStructuresMod2.zip) 
    UCHIJ   StatusEffectHUD{1.27} [StatusEffectHUD]([1.7.10]StatusEffectHUD-client-1.27.zip) 
    UCHIJ   ActuallyAdditions{1.7.10-r21} [Actually Additions](ActuallyAdditions-1.7.10-r21.zip) 
    UCHIJ   AdvancedHUD{Version [0.1.8] for 1.7.10} [AdvancedHUD](AdvancedHUD[0.1.8].jar) 
    UCHIJ   alluwant{2.1} [All U Want](All-U-Want 2.1.jar) 
    UCHIJ   animatedplayer{1.5.1} [Animated Player Mod](AnimatedPlayer-1.7.10-1.5.1.zip) 
    UCHIJ   AnimationAPI{1.2.4} [AnimationAPI](AnimationAPI-1.7.10-1.2.4.zip) 
    UCHIJ   Aquaculture{1.2.3} [Aquaculture](Aquaculture-1.7.10-1.2.5.15.zip) 
    UCHIJ   thebombzenapi{2.4.2} [ThebombzenAPI](ThebombzenAPI-v2.4.2-mc1.7.10.jar) 
    UCHIJ   autoswitch{5.1.1} [AutoSwitch](AutoSwitch-v5.1.1-mc1.7.10.jar) 
    UCHIJ   bis{3.1.1} [Back in Slime Mod](Back in Slime-1.7.10-3.1.1.zip) 
    UCHIJ   betterrecords{@VERSION@} [Better Records](BetterRecords-1.7.10-1.2.0.zip) 
    UCHIJ   betterstorage{0.13.1.127} [BetterStorage](BetterStorage-1.7.10-0.13.1.127.jar) 
    UCHIJ   bladecraft{2.0.0.1} [Bladecraft](Bladecraft 2.0.0.1.jar) 
    UCHIJ   Blocks3D{1.7.2.1} [3D Blocks Mod](Blocks3DMod-1.7.10.1.jar) 
    UCHIJ   butterflymania{1.3.2} [Butterfly Mania](butterflymania-1.7.10-1.3.2.zip) 
    UCHIJ   CharacterOnGui{1.0} [CharacterOnGui](CharacterOnGui-1.7.10-1.3.jar) 
    UCHIJ   DragonMounts{r41-1.7.10} [Dragon Mounts](DragonMounts-r41-1.7.10.jar) 
    UCHIJ   endercore{1.7.10-0.2.0.31_beta} [EnderCore](EnderCore-1.7.10-0.2.0.31_beta.zip) 
    UCHIJ   flansmod{4.10.0} [Flan's Mod](Flans Mod-1.7.10-4.10.0.jar) 
    UCHIJ   flowercraftmod{1.9} [Flowercraft](Flowercraftmod 1.8 - 1.7.10 Forge.jar) 
    UCHIJ   haycraftmod{1.7} [Haycraft](Haycraftmod 1.7 - 1.7.10 Forge.jar) 
    UCHIJ   HopperDuctMod{1.3.2} [Hopper Ducts](hopperductmod-1.7.10-1.3.2.zip) 
    UCHIJ   IGWMod{1.1.12-34} [In-Game wiki Mod](IGW-Mod-1.7.10-1.1.12-34-universal.zip) 
    UCHIJ   imc{1.7.4} [Improving Minecraft](Improving Minecraft-1.7.4.jar) 
    UCHIJ   instantblocks{1.5.4} [Instant Blocks](InstantBlocks_v1.5.4.zip) 
    UCHIJ   ism{0.6.0a} [Instant Structures Mod (ISM)](ism-0.6.0a.jar) 
    UCHIJ   jacb{1.0.4} [JACB](JACB-1.7.10-1.0.4.zip) 
    UCHIJ   harvestcraft{1.7.10j} [Pam's HarvestCraft](Pam's HarvestCraft 1.7.10Lb.zip) 
    UCHIJ   jaffa{1.62.12} [JAFFA (HarvestCraft Addon)](JAFFA-1.62.12.zip) 
    UCHIJ   kitchenCraftFoods{1.0.0} [KitchenCraft - Foods](KitchenCraft-MC1.7.10-1.0.0-63-combo.zip) 
    UCHIJ   kitchenCraftMachines{1.0.0} [KitchenCraft - Machines](KitchenCraft-MC1.7.10-1.0.0-63-combo.zip) 
    UCHIJ   LotsOfFood{1.7.10} [Lots of Food](Lots of Food-1.7.10 v7.jar) 
    UCHIJ   MagicYarn{1.1.5} [Magic Yarn](MagicYarn-1.7.10.jar) 
    UCHIJ   MedicineCraft{V4.0} [MedicineCraft](MedicineCraft V4.2.jar) 
    UCHIJ   MetallurgyCore{4.0.4} [Metallurgy Core](MetallurgyCore-1.7.10-4.0.4.18.zip) 
    UCHIJ   Metallurgy{4.0.6} [Metallurgy 4](Metallurgy-1.7.10-4.0.6.80.zip) 
    UCHIJ   minechem{5.0.5.406} [Minechem](Minechem-1.7.10-5.0.5.406.zip) 
    UCHIJ   mozombies{2.1.1} [Mo' Zombies](Mo' Zombies 2.1.1.jar) 
    UCHIJ   iChunUtil{4.2.2} [iChunUtil](iChunUtil-4.2.2.zip) 
    UCHIJ   MobDismemberment{4.0.0} [MobDismemberment](MobDismemberment-4.0.0.zip) 
    UCHIJ   bettercraft{2.7.3} [MoreCraft](MoreCraft-1.7.10-2.7.3.zip) 
    UCHIE   Morph{0.9.2} [Morph](Morph-Beta-0.9.2.zip) 
    UCHIJ   cfm{3.4.8} [§9MrCrayfish's Furniture Mod](MrCrayfishFurnitureModv3.4.8%281.7.10%29.zip) 
    UCHIJ   notenoughIDs{1.4.2} [NotEnoughIDs](NotEnoughIDs-1.4.2.zip) 
    UCHIJ   parachutemod{1.7.10} [Parachute Mod](parachutemod-1.7.10-2.5.6-01.zip) 
    UCHIJ   reptilemod{1.7.10} [Reptile Mod](reptilemod-1.7.10-2.5.6-10.zip) 
    UCHIJ   Revamp{1.3.1} [Revamp](Revamp-1.3.1.zip) 
    UCHIJ   slabcraftmod{1.7} [Slabcraft](Slabcraftmod 1.7 - 1.7.10 Forge.jar) 
    UCHIJ   LunatriusCore{1.1.2.21} [LunatriusCore](LunatriusCore-1.7.10-1.1.2.21-universal.zip) 
    UCHIJ   Stackie{1.6.0.36} [Stackie](Stackie-1.7.10-1.6.0.36-universal.zip) 
    UCHIJ   staircraftmod{1.7} [Staircraft](Staircraftmod 1.7 - 1.7.10 Forge.jar) 
    UCHIJ   wallcraftmod{1.0} [wallcraftmod](Wallcraftmod 1.0 - 1.7.10 Forge.jar) 
    GL info: ' Vendor: 'ATI Technologies Inc.' Version: '3.3.11672 Compatibility Profile Context' Renderer: 'ATI Radeon HD 3400 Series'

**Comment by Tamaized** [comment]
My guess is Optifine knowing how they edit base classes and all, try it without Optifine and see what happens.

**Comment by iChun** [comment]
Optifine could be one, the other would be iChunUtil, where did you get that
copy of iChunUtil from?

**Comment by Hans5958** [comment]
Too bad, I deleted the mods from my computer.
Request for closing (or what?)

**Comment by Tamaized** [comment]
You can close it yourself ...?

**Comment by Hans5958** [comment]
Closed.
