### ISSUE TITLE
Morph Internal Server Error 

### ISSUE THREAD

**Issue by brad18** [iChun/Morph#798]
Getting this error when attempting to join a server. It appears to be a problem with Morph.

LOG

[17:30:35] [main/INFO]: Setting user: UndercoverQuasar
[17:30:39] [Client thread/INFO]: LWJGL Version: 2.9.1
[17:31:18] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Not Enough Items, FMLFileResourcePack:Another One Bites The Dust, FMLFileResourcePack:Applied Energistics 2, FMLFileResourcePack:BD Lib, FMLFileResourcePack:BiblioCraft, FMLFileResourcePack:BiblioWoods Biomes O'Plenty Edition, FMLFileResourcePack:BiblioWoods Forestry Edition, FMLFileResourcePack:BiblioWoods Natura Edition, FMLFileResourcePack:Big Reactors, FMLFileResourcePack:Botany, FMLFileResourcePack:Binnie Core, FMLFileResourcePack:Extra Bees, FMLFileResourcePack:Extra Trees, FMLFileResourcePack:Genetics, FMLFileResourcePack:Biomes O' Plenty, FMLFileResourcePack:Blood Magic: Alchemical Wizardry, FMLFileResourcePack:Botania, FMLFileResourcePack:BC Builders, FMLFileResourcePack:BC Transport, FMLFileResourcePack:BC Energy, FMLFileResourcePack:BC Silicon, FMLFileResourcePack:BC Robotics, FMLFileResourcePack:BuildCraft, FMLFileResourcePack:BC Factory, FMLFileResourcePack:BuildCraft Compat, FMLFileResourcePack:Carpenter's Blocks, FMLFileResourcePack:ChickenChunks, FMLFileResourcePack:Chisel, FMLFileResourcePack:CoFH Core, FMLFileResourcePack:Compact Solar Arrays, FMLFileResourcePack:ComputerCraft, FMLFileResourcePack:Custom Main Menu, FMLFileResourcePack:debug, FMLFileResourcePack:Dense Ores, FMLFileResourcePack:EnderCore, FMLFileResourcePack:Ender IO, FMLFileResourcePack:EnderStorage, FMLFileResourcePack:EnderTech, FMLFileResourcePack:Ender Zoo, FMLFileResourcePack:Extra Utilities, FMLFileResourcePack:Factorization Miscellaneous Nonsense, FMLFileResourcePack:Factorization Notification System, FMLFileResourcePack:Factorization Dimensional Slices, FMLFileResourcePack:Factorization, FMLFileResourcePack:FastCraft, FMLFileResourcePack:Flat Signs, FMLFileResourcePack:Forestry for Minecraft, FMLFileResourcePack:FTBLib, FMLFileResourcePack:FTBUtilities, FMLFileResourcePack:Funky Locomotion, FMLFileResourcePack:GenDustry, FMLFileResourcePack:Guide-API, FMLFileResourcePack:Hats, FMLFileResourcePack:HatStand, FMLFileResourcePack:HelpFixer, FMLFileResourcePack:Nuclear Control 2, FMLFileResourcePack:iChunUtil, FMLFileResourcePack:IndustrialCraft 2, FMLFileResourcePack:INpureCore, FMLFileResourcePack:Inventory Tweaks, FMLFileResourcePack:Iron Chest, FMLFileResourcePack:JABBA, FMLFileResourcePack:JourneyMap, FMLFileResourcePack:Magic Bees, FMLFileResourcePack:Mantle, FMLFileResourcePack:MineFactory Reloaded, FMLFileResourcePack:MFR Compat: Applied Energistics, FMLFileResourcePack:MFR Compat: Atum, FMLFileResourcePack:MFR Compat: BackTools, FMLFileResourcePack:MFR Compat: BuildCraft, FMLFileResourcePack:MFR Compat: Chococraft, FMLFileResourcePack:MFR Compat: ExtraBiomes, FMLFileResourcePack:MFR Compat: Forestry, FMLFileResourcePack:MFR Compat: ForgeMicroblock, FMLFileResourcePack:MFR Compat: IC2, FMLFileResourcePack:MFR Compat: Mystcraft, FMLFileResourcePack:MFR Compat ProjectRed, FMLFileResourcePack:MFR Compat: Railcraft, FMLFileResourcePack:MFR Compat: Sufficient Biomes, FMLFileResourcePack:MFR Compat: Thaumcraft, FMLFileResourcePack:MFR Compat: Thermal Expansion, FMLFileResourcePack:MFR Compat: Tinkers' Construct, FMLFileResourcePack:MFR Compat: TwilightForest, FMLFileResourcePack:MFR Compat: Vanilla, FMLFileResourcePack:MineTweaker 3, FMLFileResourcePack:MachineMuse's Modular Powersuits, FMLFileResourcePack:Morph, FMLFileResourcePack:Morpheus, FMLFileResourcePack:Mystcraft, FMLFileResourcePack:Natura, FMLFileResourcePack:NEI Addons, FMLFileResourcePack:NEI Addons: Developer Tools, FMLFileResourcePack:NEI Addons: Applied Energistics 2, FMLFileResourcePack:NEI Addons: Botany, FMLFileResourcePack:NEI Addons: Forestry, FMLFileResourcePack:NEI Addons: Crafting Tables, FMLFileResourcePack:NEI Addons: Ex Nihilo, FMLFileResourcePack:NEI Integration, FMLFileResourcePack:NotEnoughCodecs, FMLFileResourcePack:NotEnoughKeys, FMLFileResourcePack:Numina, FMLFileResourcePack:ObsidiPlates, FMLFileResourcePack:OpenBlocks, FMLFileResourcePack:OpenMods, FMLFileResourcePack:OpenPeripheralAddons, FMLFileResourcePack:OpenPeripheralCore, FMLFileResourcePack:OpenPeripheralIntegration, FMLFileResourcePack:PneumaticCraft, FMLFileResourcePack:PortalGun, FMLFileResourcePack:ProjectRed Core, FMLFileResourcePack:ProjectRed Compatibility, FMLFileResourcePack:ProjectRed Integration, FMLFileResourcePack:ProjectRed Transmission, FMLFileResourcePack:ProjectRed Illumination, FMLFileResourcePack:ProjectRed Exploration, FMLFileResourcePack:Railcraft, FMLFileResourcePack:Redstone Arsenal, FMLFileResourcePack:Resource Loader, FMLFileResourcePack:RFTools, FMLFileResourcePack:Steve's Carts 2, FMLFileResourcePack:Steve's Factory Manager, FMLFileResourcePack:Tinkers' Construct, FMLFileResourcePack:Thaumcraft, FMLFileResourcePack:Thaumic Exploration, FMLFileResourcePack:Thaumic Tinkerer, FMLFileResourcePack:Thermal Dynamics, FMLFileResourcePack:Thermal Expansion, FMLFileResourcePack:Thermal Foundation, FMLFileResourcePack:TiC Tooltips, FMLFileResourcePack:Tinkers' Mechworks, FMLFileResourcePack:Translocator, FMLFileResourcePack:The Twilight Forest, FMLFileResourcePack:Waila, FMLFileResourcePack:Waila Harvestability, FMLFileResourcePack:Witchery, FMLFileResourcePack:WR-CBE Core, FMLFileResourcePack:WR-CBE Addons, FMLFileResourcePack:WR-CBE Logic, FMLFileResourcePack:Baubles, FMLFileResourcePack:Forge Microblocks, FMLFileResourcePack:Forge Multipart, FMLFileResourcePack:Minecraft Multipart Plugin, FMLFileResourcePack:MrTJPCore
[17:31:18] [Client thread/WARN]: ResourcePack: ignored non-lowercase namespace: alchemicalwizardryBooks in C:\Users\Bradley\Documents\Curse\Minecraft\Instances\FTB Presents Direwolf20\mods\BloodMagic-1.7.10-1.3.3-17.jar
[17:31:18] [Client thread/WARN]: ResourcePack: ignored non-lowercase namespace: alchemicalwizardryBooks in C:\Users\Bradley\Documents\Curse\Minecraft\Instances\FTB Presents Direwolf20\mods\BloodMagic-1.7.10-1.3.3-17.jar
[17:31:18] [Client thread/WARN]: ResourcePack: ignored non-lowercase namespace: alchemicalwizardryBooks in C:\Users\Bradley\Documents\Curse\Minecraft\Instances\FTB Presents Direwolf20\mods\BloodMagic-1.7.10-1.3.3-17.jar
[17:31:18] [Client thread/WARN]: ResourcePack: ignored non-lowercase namespace: alchemicalwizardryBooks in C:\Users\Bradley\Documents\Curse\Minecraft\Instances\FTB Presents Direwolf20\mods\BloodMagic-1.7.10-1.3.3-17.jar
[17:31:18] [Client thread/WARN]: ResourcePack: ignored non-lowercase namespace: alchemicalwizardryBooks in C:\Users\Bradley\Documents\Curse\Minecraft\Instances\FTB Presents Direwolf20\mods\BloodMagic-1.7.10-1.3.3-17.jar
[17:31:18] [Client thread/WARN]: ResourcePack: ignored non-lowercase namespace: alchemicalwizardryBooks in C:\Users\Bradley\Documents\Curse\Minecraft\Instances\FTB Presents Direwolf20\mods\BloodMagic-1.7.10-1.3.3-17.jar
[17:32:02] [Sound Library Loader/INFO]: Sound engine started
[17:32:04] [Client thread/INFO]: Created: 16x16 textures/blocks-atlas
[17:32:05] [Client thread/INFO]: Created: 16x16 textures/items-atlas
[17:32:58] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Not Enough Items, FMLFileResourcePack:Another One Bites The Dust, FMLFileResourcePack:Applied Energistics 2, FMLFileResourcePack:BD Lib, FMLFileResourcePack:BiblioCraft, FMLFileResourcePack:BiblioWoods Biomes O'Plenty Edition, FMLFileResourcePack:BiblioWoods Forestry Edition, FMLFileResourcePack:BiblioWoods Natura Edition, FMLFileResourcePack:Big Reactors, FMLFileResourcePack:Botany, FMLFileResourcePack:Binnie Core, FMLFileResourcePack:Extra Bees, FMLFileResourcePack:Extra Trees, FMLFileResourcePack:Genetics, FMLFileResourcePack:Biomes O' Plenty, FMLFileResourcePack:Blood Magic: Alchemical Wizardry, FMLFileResourcePack:Botania, FMLFileResourcePack:BC Builders, FMLFileResourcePack:BC Transport, FMLFileResourcePack:BC Energy, FMLFileResourcePack:BC Silicon, FMLFileResourcePack:BC Robotics, FMLFileResourcePack:BuildCraft, FMLFileResourcePack:BC Factory, FMLFileResourcePack:BuildCraft Compat, FMLFileResourcePack:Carpenter's Blocks, FMLFileResourcePack:ChickenChunks, FMLFileResourcePack:Chisel, FMLFileResourcePack:CoFH Core, FMLFileResourcePack:Compact Solar Arrays, FMLFileResourcePack:ComputerCraft, FMLFileResourcePack:Custom Main Menu, FMLFileResourcePack:debug, FMLFileResourcePack:Dense Ores, FMLFileResourcePack:EnderCore, FMLFileResourcePack:Ender IO, FMLFileResourcePack:EnderStorage, FMLFileResourcePack:EnderTech, FMLFileResourcePack:Ender Zoo, FMLFileResourcePack:Extra Utilities, FMLFileResourcePack:Factorization Miscellaneous Nonsense, FMLFileResourcePack:Factorization Notification System, FMLFileResourcePack:Factorization Dimensional Slices, FMLFileResourcePack:Factorization, FMLFileResourcePack:FastCraft, FMLFileResourcePack:Flat Signs, FMLFileResourcePack:Forestry for Minecraft, FMLFileResourcePack:FTBLib, FMLFileResourcePack:FTBUtilities, FMLFileResourcePack:Funky Locomotion, FMLFileResourcePack:GenDustry, FMLFileResourcePack:Guide-API, FMLFileResourcePack:Hats, FMLFileResourcePack:HatStand, FMLFileResourcePack:HelpFixer, FMLFileResourcePack:Nuclear Control 2, FMLFileResourcePack:iChunUtil, FMLFileResourcePack:IndustrialCraft 2, FMLFileResourcePack:INpureCore, FMLFileResourcePack:Inventory Tweaks, FMLFileResourcePack:Iron Chest, FMLFileResourcePack:JABBA, FMLFileResourcePack:JourneyMap, FMLFileResourcePack:Magic Bees, FMLFileResourcePack:Mantle, FMLFileResourcePack:MineFactory Reloaded, FMLFileResourcePack:MFR Compat: Applied Energistics, FMLFileResourcePack:MFR Compat: Atum, FMLFileResourcePack:MFR Compat: BackTools, FMLFileResourcePack:MFR Compat: BuildCraft, FMLFileResourcePack:MFR Compat: Chococraft, FMLFileResourcePack:MFR Compat: ExtraBiomes, FMLFileResourcePack:MFR Compat: Forestry, FMLFileResourcePack:MFR Compat: ForgeMicroblock, FMLFileResourcePack:MFR Compat: IC2, FMLFileResourcePack:MFR Compat: Mystcraft, FMLFileResourcePack:MFR Compat ProjectRed, FMLFileResourcePack:MFR Compat: Railcraft, FMLFileResourcePack:MFR Compat: Sufficient Biomes, FMLFileResourcePack:MFR Compat: Thaumcraft, FMLFileResourcePack:MFR Compat: Thermal Expansion, FMLFileResourcePack:MFR Compat: Tinkers' Construct, FMLFileResourcePack:MFR Compat: TwilightForest, FMLFileResourcePack:MFR Compat: Vanilla, FMLFileResourcePack:MineTweaker 3, FMLFileResourcePack:MachineMuse's Modular Powersuits, FMLFileResourcePack:Morph, FMLFileResourcePack:Morpheus, FMLFileResourcePack:Mystcraft, FMLFileResourcePack:Natura, FMLFileResourcePack:NEI Addons, FMLFileResourcePack:NEI Addons: Developer Tools, FMLFileResourcePack:NEI Addons: Applied Energistics 2, FMLFileResourcePack:NEI Addons: Botany, FMLFileResourcePack:NEI Addons: Forestry, FMLFileResourcePack:NEI Addons: Crafting Tables, FMLFileResourcePack:NEI Addons: Ex Nihilo, FMLFileResourcePack:NEI Integration, FMLFileResourcePack:NotEnoughCodecs, FMLFileResourcePack:NotEnoughKeys, FMLFileResourcePack:Numina, FMLFileResourcePack:ObsidiPlates, FMLFileResourcePack:OpenBlocks, FMLFileResourcePack:OpenMods, FMLFileResourcePack:OpenPeripheralAddons, FMLFileResourcePack:OpenPeripheralCore, FMLFileResourcePack:OpenPeripheralIntegration, FMLFileResourcePack:PneumaticCraft, FMLFileResourcePack:PortalGun, FMLFileResourcePack:ProjectRed Core, FMLFileResourcePack:ProjectRed Compatibility, FMLFileResourcePack:ProjectRed Integration, FMLFileResourcePack:ProjectRed Transmission, FMLFileResourcePack:ProjectRed Illumination, FMLFileResourcePack:ProjectRed Exploration, FMLFileResourcePack:Railcraft, FMLFileResourcePack:Redstone Arsenal, FMLFileResourcePack:Resource Loader, FMLFileResourcePack:RFTools, FMLFileResourcePack:Steve's Carts 2, FMLFileResourcePack:Steve's Factory Manager, FMLFileResourcePack:Tinkers' Construct, FMLFileResourcePack:Thaumcraft, FMLFileResourcePack:Thaumic Exploration, FMLFileResourcePack:Thaumic Tinkerer, FMLFileResourcePack:Thermal Dynamics, FMLFileResourcePack:Thermal Expansion, FMLFileResourcePack:Thermal Foundation, FMLFileResourcePack:TiC Tooltips, FMLFileResourcePack:Tinkers' Mechworks, FMLFileResourcePack:Translocator, FMLFileResourcePack:The Twilight Forest, FMLFileResourcePack:Waila, FMLFileResourcePack:Waila Harvestability, FMLFileResourcePack:Witchery, FMLFileResourcePack:WR-CBE Core, FMLFileResourcePack:WR-CBE Addons, FMLFileResourcePack:WR-CBE Logic, FMLFileResourcePack:Baubles, FMLFileResourcePack:Forge Microblocks, FMLFileResourcePack:Forge Multipart, FMLFileResourcePack:Minecraft Multipart Plugin, FMLFileResourcePack:MrTJPCore, PortalGunSounds.pak, CustomResources, FMLFileResourcePack:Carpenter's Blocks Cached Resources, XU_Delegate_Pack, XU_Delegate_Pack, XU_Delegate_Pack, CustomOverridingResources
[17:32:58] [Client thread/WARN]: ResourcePack: ignored non-lowercase namespace: alchemicalwizardryBooks in C:\Users\Bradley\Documents\Curse\Minecraft\Instances\FTB Presents Direwolf20\mods\BloodMagic-1.7.10-1.3.3-17.jar
[17:32:58] [Client thread/WARN]: ResourcePack: ignored non-lowercase namespace: alchemicalwizardryBooks in C:\Users\Bradley\Documents\Curse\Minecraft\Instances\FTB Presents Direwolf20\mods\BloodMagic-1.7.10-1.3.3-17.jar
[17:32:58] [Client thread/WARN]: ResourcePack: ignored non-lowercase namespace: alchemicalwizardryBooks in C:\Users\Bradley\Documents\Curse\Minecraft\Instances\FTB Presents Direwolf20\mods\BloodMagic-1.7.10-1.3.3-17.jar
[17:32:58] [Client thread/WARN]: ResourcePack: ignored non-lowercase namespace: alchemicalwizardryBooks in C:\Users\Bradley\Documents\Curse\Minecraft\Instances\FTB Presents Direwolf20\mods\BloodMagic-1.7.10-1.3.3-17.jar
[17:32:58] [Client thread/WARN]: ResourcePack: ignored non-lowercase namespace: alchemicalwizardryBooks in C:\Users\Bradley\Documents\Curse\Minecraft\Instances\FTB Presents Direwolf20\mods\BloodMagic-1.7.10-1.3.3-17.jar
[17:32:58] [Client thread/WARN]: ResourcePack: ignored non-lowercase namespace: alchemicalwizardryBooks in C:\Users\Bradley\Documents\Curse\Minecraft\Instances\FTB Presents Direwolf20\mods\BloodMagic-1.7.10-1.3.3-17.jar
[17:33:01] [Client thread/ERROR]: Unable to parse metadata from thaumicexploration:textures/blocks/soulBrazier.png
java.lang.RuntimeException: broken aspect ratio and not an animation
    at net.minecraft.client.renderer.texture.TextureAtlasSprite.func_147964_a(TextureAtlasSprite.java:273) ~[bqd.class:?]
    at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:242) [bpz.class:?]
    at net.minecraft.client.renderer.texture.TextureMap.func_110551_a(TextureMap.java:136) [bpz.class:?]
    at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:94) [bqf.class:?]
    at net.minecraft.client.renderer.texture.TextureManager.func_110549_a(TextureManager.java:200) [bqf.class:?]
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:143) [brg.class:?]
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:121) [brg.class:?]
    at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:609) [bao.class:?]
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:327) [FMLClientHandler.class:?]
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552) [bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
    at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[17:33:01] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/blocks/MISSING_ICON_BLOCK_461_bookshelf.png, java.io.FileNotFoundException
[17:33:02] [Client thread/ERROR]: Using missing texture, unable to load ttinkerer:textures/blocks/repairer.png, java.io.FileNotFoundException
[17:33:02] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/blocks/MISSING_ICON_BLOCK_881_blockSpellParadigm.png, java.io.FileNotFoundException
[17:33:03] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/blocks/MISSING_ICON_BLOCK_889_alchemicCalcinator.png, java.io.FileNotFoundException
[17:33:03] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/blocks/TConIntegration.bedrock.png, java.io.FileNotFoundException
[17:33:04] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/blocks/planks.png, java.io.FileNotFoundException
[17:33:04] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/blocks/MISSING_ICON_BLOCK_884_blockSpellEffect.png, java.io.FileNotFoundException
[17:33:04] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/blocks/MISSING_ICON_BLOCK_882_blockSpellEnhancement.png, java.io.FileNotFoundException
[17:33:05] [Client thread/ERROR]: Using missing texture, unable to load chisel:textures/blocks/endstone/EnderFrame.png, java.io.FileNotFoundException
[17:33:05] [Client thread/ERROR]: Using missing texture, unable to load ttinkerer:textures/blocks/magnet.png, java.io.FileNotFoundException
[17:33:05] [Client thread/ERROR]: Using missing texture, unable to load thaumicexploration:textures/blocks/metalbase.png, java.io.FileNotFoundException
[17:33:05] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/blocks/MISSING_ICON_BLOCK_883_blockSpellModifier.png, java.io.FileNotFoundException
[17:33:05] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/blocks/MISSING_ICON_BLOCK_2107_proxyBlock.png, java.io.FileNotFoundException
[17:33:05] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/blocks/MISSING_ICON_BLOCK_887_schematicSaver.png, java.io.FileNotFoundException
[17:33:06] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/blocks/MISSING_ICON_BLOCK_890_crystalBelljar.png, java.io.FileNotFoundException
[17:33:07] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/blocks/MISSING_ICON_BLOCK_893_blockMimic.png, java.io.FileNotFoundException
[17:33:07] [Client thread/INFO]: textures/blocks: dropping miplevel from 4 to 3, because of minTexel: 8
[17:33:07] [Client thread/INFO]: Created: 4096x2048 textures/blocks-atlas
[17:33:09] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/items/MISSING_ICON_ITEM_5998_logisticFrameStorage.png, java.io.FileNotFoundException
[17:33:09] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/items/MISSING_ICON_ITEM_6013_heatFrame.png, java.io.FileNotFoundException
[17:33:09] [Client thread/ERROR]: Using missing texture, unable to load pneumaticcraft:textures/items/cannonBarrel.png, java.io.FileNotFoundException
[17:33:09] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/items/MISSING_ICON_ITEM_6257_focusSmelt.png, java.io.FileNotFoundException
[17:33:09] [Client thread/ERROR]: Using missing texture, unable to load buildcraft:textures/items/triggers/trigger_machine_inactive.png, java.io.FileNotFoundException
[17:33:09] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/items/MISSING_ICON_ITEM_6236_focusHeal.png, java.io.FileNotFoundException
[17:33:09] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/items/MISSING_ICON_ITEM_6252_focusDeflect.png, java.io.FileNotFoundException
[17:33:09] [Client thread/ERROR]: Using missing texture, unable to load missing_icon_item_5700_extrautils:textures/items/microblocks.png, java.io.FileNotFoundException
[17:33:09] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/items/MISSING_ICON_ITEM_5996_logisticFrameRequester.png, java.io.FileNotFoundException
[17:33:09] [Client thread/ERROR]: Using missing texture, unable to load ttinkerer:textures/items/ichorPickGem.png, java.io.FileNotFoundException
[17:33:09] [Client thread/ERROR]: Using missing texture, unable to load ttinkerer:textures/items/mobAspect.png, java.io.FileNotFoundException
[17:33:09] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/items/MISSING_ICON_ITEM_5999_logisticFramePassiveProvider.png, java.io.FileNotFoundException
[17:33:10] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/items/MISSING_ICON_ITEM_6270_focusFlight.png, java.io.FileNotFoundException
[17:33:10] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/items/MISSING_ICON_ITEM_6245_focusTelekinesis.png, java.io.FileNotFoundException
[17:33:10] [Client thread/ERROR]: Using missing texture, unable to load missing_icon_item_5683_extrautils:textures/items/lawSword.png, java.io.FileNotFoundException
[17:33:10] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/items/MISSING_ICON_ITEM_6237_focusDislocation.png, java.io.FileNotFoundException
[17:33:10] [Client thread/ERROR]: Using missing texture, unable to load ttinkerer:textures/items/ichorShovelGem.png, java.io.FileNotFoundException
[17:33:10] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/items/MISSING_ICON_ITEM_6000_logisticFrameActiveProvider.png, java.io.FileNotFoundException
[17:33:10] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/items/MISSING_ICON_ITEM_6244_focusXPDrain.png, java.io.FileNotFoundException
[17:33:10] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/items/MISSING_ICON_BLOCK_1025_gaiaHeadBlock_skeleton.png, java.io.FileNotFoundException
[17:33:10] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/items/MISSING_ICON_ITEM_6253_focusShadowbeam.png, java.io.FileNotFoundException
[17:33:10] [Client thread/ERROR]: Using missing texture, unable to load ttinkerer:textures/items/ichorSwordGem.png, java.io.FileNotFoundException
[17:33:10] [Client thread/ERROR]: Using missing texture, unable to load ttinkerer:textures/items/ichorAxeGem.png, java.io.FileNotFoundException
[17:33:10] [Client thread/ERROR]: Using missing texture, unable to load minefactoryreloaded:textures/items/item.mfr.rednet.meter.debug.png, java.io.FileNotFoundException
[17:33:11] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/items/MISSING_ICON_ITEM_6234_focusRecall.png, java.io.FileNotFoundException
[17:33:11] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/items/MISSING_ICON_ITEM_5997_logisticFrameDefaultStorage.png, java.io.FileNotFoundException
[17:33:11] [Client thread/ERROR]: Using missing texture, unable to load buildcraft:textures/items/triggers/trigger_machine_active.png, java.io.FileNotFoundException
[17:33:11] [Client thread/ERROR]: Using missing texture, unable to load alchemicalwizardry:textures/items/SigilOfTheFastMiner.png, java.io.FileNotFoundException
[17:33:11] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/items/MISSING_ICON_ITEM_6264_focusEnderChest.png, java.io.FileNotFoundException
[17:33:11] [Client thread/INFO]: Created: 2048x2048 textures/items-atlas
[17:33:12] [Sound Library Loader/INFO]: Sound engine started
[17:33:21] [Client thread/INFO]: Connecting to 78.129.165.196, 25565
[17:33:25] [Client thread/INFO]: [CHAT] Welcome to the server!
[17:33:26] [Client thread/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@39534154[id=XXXXXXXX-bd3a-4b46-9280-XXXXXXXXXXX,name=UndercoverQuasar,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
    at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[YggdrasilAuthenticationService.class:?]
    at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:175) [YggdrasilMinecraftSessionService.class:?]
    at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:168) [YggdrasilMinecraftSessionService.class:?]
    at ichun.common.core.EntityHelperBase.getFullGameProfileFromName(EntityHelperBase.java:109) [EntityHelperBase.class:?]
    at morph.common.morph.MorphState.createPlayer(MorphState.java:173) [MorphState.class:?]
    at morph.common.morph.MorphState.readTag(MorphState.java:123) [MorphState.class:?]
    at morph.common.packet.PacketMorphStates.handleClient(PacketMorphStates.java:83) [PacketMorphStates.class:?]
    at morph.common.packet.PacketMorphStates.execute(PacketMorphStates.java:62) [PacketMorphStates.class:?]
    at ichun.common.core.network.ChannelHandler$PacketExecuter.channelRead0(ChannelHandler.java:84) [ChannelHandler$PacketExecuter.class:?]
    at ichun.common.core.network.ChannelHandler$PacketExecuter.channelRead0(ChannelHandler.java:66) [ChannelHandler$PacketExecuter.class:?]
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [SimpleChannelInboundHandler.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
    at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
    at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78) [bcx.class:?]
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1661) [bao.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
    at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[17:33:34] [Client thread/INFO]: [CHAT] A new §eOptiFine§f version is available: §eHD Ultra D1§f
[17:33:35] [Client thread/INFO]: [CHAT] InvTweaks: Configuration loaded.
[17:33:52] [Client thread/INFO]: Stopping!

**Comment by iChun** [comment]
Is it preventing you from connecting to the server? It shouldn't though. If
it doesn't then it's all fine.

**Comment by brad18** [comment]
Yeah. It was occurring when we joined the server and we got instantly kicked. Myself and another player were getting a mixture of Java.io exceptions and internal server errors, the latter being more common. The host has disabled Morph and now I am able to join again.

**Comment by iChun** [comment]
Hmm, that ideally shouldn't be happening. Is there an error server-side?

**Comment by brad18** [comment]
Not sure.I'd have to ask the host. Do you want to see the server side log?

**Comment by iChun** [comment]
Yes please. I can't tell what wrong from the client side log.

**Comment by brad18** [comment]
Ok. I'll see what I can get from the owner.

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
