### ISSUE TITLE
Morph Mod for MC 1.7.10

### ISSUE THREAD

**Issue by JakobKarde** [iChun/Morph#809]
When starting a world with the iChunUtil 4.2.2 without morph it works fine.  As soon as I start a world with Morph, it only shows the world for a split second before it gives me the message "Shutting Down Internal Server..." and then gives me a message stating "Connection Lost  A fatal error has occured, this connection is terminated."  Here is the game output info;
[18:08:45] [Client thread/INFO] [MinecraftForge]: Attempting early MinecraftForge initialization
[18:08:45] [Client thread/INFO] [FML]: MinecraftForge v10.13.4.1481 Initialized
[18:08:45] [Client thread/INFO] [FML]: Replaced 183 ore recipies
[18:08:45] [Client thread/INFO] [MinecraftForge]: Completed early MinecraftForge initialization
[18:08:45] [Client thread/INFO] [FML]: Found 0 mods from the command line. Injecting into mod discoverer
[18:08:45] [Client thread/INFO] [FML]: Searching C:\Users\jakob\AppData\Roaming.minecraft\mods for mods
[18:08:50] [Client thread/INFO] [FML]: Forge Mod Loader has identified 5 mods to load
[18:08:50] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, iChunUtil, Morph] at CLIENT
[18:08:50] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, iChunUtil, Morph] at SERVER
[18:08:51] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:iChunUtil, FMLFileResourcePack:Morph
[18:08:51] [Client thread/INFO] [FML]: Processing ObjectHolder annotations
[18:08:51] [Client thread/INFO] [FML]: Found 341 ObjectHolder annotations
[18:08:51] [Client thread/INFO] [FML]: Identifying ItemStackHolder annotations
[18:08:51] [Client thread/INFO] [FML]: Found 0 ItemStackHolder annotations
[18:08:51] [Client thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[18:08:51] [iChunUtil Patron Getter Thread/INFO] [STDOUT]: [info.mineshafter.hacks.InterceptHttpsHandler:openConnection:38]: Should handle? https://raw.github.com/iChun/iChunUtil/master/src/main/resources/assets/ichunutil/mod/patrons.json false
[18:08:52] [Client thread/INFO] [FML]: Applying holder lookups
[18:08:52] [Client thread/INFO] [FML]: Holder lookups applied
[18:08:52] [Client thread/INFO] [FML]: Injecting itemstacks
[18:08:52] [Client thread/INFO] [FML]: Itemstack injection complete
[18:08:52] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[18:08:52] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Starting up SoundSystem...
[18:08:52] [Thread-9/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Initializing LWJGL OpenAL
[18:08:52] [Thread-9/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]:     (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[18:08:52] [Thread-9/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: OpenAL initialized.
[18:08:53] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[18:08:53] [Sound Library Loader/INFO]: Sound engine started
[18:08:55] [Client thread/INFO]: Created: 16x16 textures/blocks-atlas
[18:08:55] [Client thread/INFO]: Created: 16x16 textures/items-atlas
[18:08:55] [iChunUtil Mod Version Check/INFO] [STDOUT]: [info.mineshafter.hacks.InterceptHttpsHandler:openConnection:38]: Should handle? https://raw.github.com/iChun/iChunUtil/master/src/main/resources/assets/ichunutil/mod/versions.json false
[18:08:55] [Client thread/INFO] [FML]: Injecting itemstacks
[18:08:55] [Client thread/INFO] [FML]: Itemstack injection complete
[18:08:56] [Morph Online Resource Thread/INFO] [STDOUT]: [info.mineshafter.hacks.InterceptHttpsHandler:openConnection:38]: Should handle? https://raw.github.com/iChun/Morph/master/src/main/resources/assets/morph/mod/AbilitySupport.json false
[18:08:56] [Client thread/INFO] [FML]: Forge Mod Loader has successfully loaded 5 mods
[18:08:56] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:iChunUtil, FMLFileResourcePack:Morph
[18:08:57] [Morph Online Resource Thread/INFO] [Morph]: [0.9.0] Found and mapped ability mappings for 24 presumably Minecraft mobs.
[18:08:57] [Morph Online Resource Thread/INFO] [STDOUT]: [info.mineshafter.hacks.InterceptHttpsHandler:openConnection:38]: Should handle? https://raw.github.com/iChun/Morph/master/src/main/resources/assets/morph/mod/NBTStripper.json false
[18:08:57] [Client thread/INFO]: Created: 512x256 textures/blocks-atlas
[18:08:57] [Client thread/INFO]: Created: 256x256 textures/items-atlas
[18:08:57] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[18:08:57] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: SoundSystem shutting down...
[18:08:58] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:importantMessage:90]:     Author: Paul Lamb, www.paulscode.com
[18:08:58] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[18:08:58] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[18:08:58] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Starting up SoundSystem...
[18:08:58] [Thread-12/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Initializing LWJGL OpenAL
[18:08:58] [Thread-12/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]:     (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[18:08:58] [Thread-12/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: OpenAL initialized.
[18:08:58] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[18:08:58] [Sound Library Loader/INFO]: Sound engine started
[18:09:05] [Server thread/INFO]: Starting integrated minecraft server version 1.7.10
[18:09:05] [Server thread/INFO]: Generating keypair
[18:09:06] [Server thread/INFO]: Converting map!
[18:09:06] [Server thread/INFO]: Scanning folders...
[18:09:06] [Server thread/INFO]: Total conversion count is 0
[18:09:06] [Server thread/INFO] [FML]: Injecting existing block and item data into this server instance
[18:09:06] [Server thread/INFO] [FML]: Applying holder lookups
[18:09:06] [Server thread/INFO] [FML]: Holder lookups applied
[18:09:07] [Server thread/INFO] [FML]: Loading dimension 0 (New World) (net.minecraft.server.integrated.IntegratedServer@27e99)
[18:09:07] [Server thread/INFO] [FML]: Loading dimension 1 (New World) (net.minecraft.server.integrated.IntegratedServer@27e99)
[18:09:07] [Server thread/INFO] [FML]: Loading dimension -1 (New World) (net.minecraft.server.integrated.IntegratedServer@27e99)
[18:09:07] [Server thread/INFO]: Preparing start region for level 0
[18:09:08] [Server thread/INFO]: Preparing spawn area: 7%
[18:09:09] [Server thread/INFO]: Preparing spawn area: 14%
[18:09:10] [Server thread/INFO]: Preparing spawn area: 19%
[18:09:11] [Server thread/INFO]: Preparing spawn area: 25%
[18:09:12] [Server thread/INFO]: Preparing spawn area: 30%
[18:09:13] [Server thread/INFO]: Preparing spawn area: 35%
[18:09:14] [Server thread/INFO]: Preparing spawn area: 40%
[18:09:15] [Server thread/INFO]: Preparing spawn area: 46%
[18:09:16] [Server thread/INFO]: Preparing spawn area: 51%
[18:09:17] [Server thread/INFO]: Preparing spawn area: 56%
[18:09:18] [Server thread/INFO]: Preparing spawn area: 61%
[18:09:19] [Server thread/INFO]: Preparing spawn area: 64%
[18:09:20] [Server thread/INFO]: Preparing spawn area: 70%
[18:09:21] [Server thread/INFO]: Preparing spawn area: 76%
[18:09:22] [Server thread/INFO]: Preparing spawn area: 83%
[18:09:23] [Server thread/INFO]: Preparing spawn area: 89%
[18:09:24] [Server thread/INFO]: Preparing spawn area: 96%
[18:09:25] [Server thread/INFO]: Changing view distance to 6, from 10
[18:09:26] [Netty Client IO #0/INFO] [FML]: Server protocol version 2
[18:09:26] [Netty IO #1/INFO] [FML]: Client protocol version 2
[18:09:26] [Netty IO #1/INFO] [FML]: Client attempting to join with 5 mods : FML@7.10.99.99,Forge@10.13.4.1481,Morph@0.9.0,mcp@9.05,iChunUtil@4.2.2
[18:09:26] [Netty IO #1/INFO] [FML]: Attempting connection with missing mods [] at CLIENT
[18:09:26] [Netty Client IO #0/INFO] [FML]: Attempting connection with missing mods [] at SERVER
[18:09:26] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
[18:09:26] [Server thread/INFO]: JakobKarde[local:E:4a0b20d7] logged in with entity id 148 at (-147.5, 103.0, 271.5)
[18:09:26] [Client thread/INFO] [FML]: [Client thread] Client side modded connection established
[18:09:26] [Server thread/INFO]: JakobKarde joined the game
[18:09:26] [Client thread/INFO] [STDOUT]: [info.mineshafter.hacks.InterceptHttpsHandler:openConnection:38]: Should handle? https://api.mojang.com/profiles/minecraft true
[18:09:26] [Client thread/ERROR] [FML]: There was a critical exception handling a packet on channel Morph
java.lang.NullPointerException
    at com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository.findProfilesByNames(YggdrasilGameProfileRepository.java:53) ~[YggdrasilGameProfileRepository.class:?]
    at ichun.common.core.EntityHelperBase.getPartialGameProfileFromName(EntityHelperBase.java:151) ~[EntityHelperBase.class:?]
    at ichun.common.core.EntityHelperBase.getFullGameProfileFromName(EntityHelperBase.java:101) ~[EntityHelperBase.class:?]
    at morph.common.morph.MorphState.createPlayer(MorphState.java:173) ~[MorphState.class:?]
    at morph.common.morph.MorphState.readTag(MorphState.java:123) ~[MorphState.class:?]
    at morph.common.packet.PacketMorphStates.handleClient(PacketMorphStates.java:83) ~[PacketMorphStates.class:?]
    at morph.common.packet.PacketMorphStates.execute(PacketMorphStates.java:62) ~[PacketMorphStates.class:?]
    at ichun.common.core.network.ChannelHandler$PacketExecuter.channelRead0(ChannelHandler.java:84) ~[ChannelHandler$PacketExecuter.class:?]
    at ichun.common.core.network.ChannelHandler$PacketExecuter.channelRead0(ChannelHandler.java:66) ~[ChannelHandler$PacketExecuter.class:?]
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[MessageToMessageDecoder.class:?]
    at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2061) [bao.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
    at info.mineshafter.GameStarter.main(GameStarter.java:24) [ms-starter.jar:?]
[18:09:26] [pool-2-thread-1/INFO] [STDOUT]: [info.mineshafter.hacks.InterceptHttpsHandler:openConnection:38]: Should handle? https://sessionserver.mojang.com/session/minecraft/profile/023b57e6c8738d474909cb04588c0f32?unsigned=true true
[18:09:26] [pool-2-thread-1/INFO] [STDOUT]: [info.mineshafter.intercept.ProfileHandler:getProfile:73]: ProfileHandler.getProfile(023b57e6c8738d474909cb04588c0f32)
[18:09:26] [pool-2-thread-1/INFO] [STDOUT]: [info.mineshafter.datasources.MineshafterProfileAuthority:getProfile:36]: MineshafterProfileClient.getProfile(023b57e6c8738d474909cb04588c0f32)
[18:09:27] [pool-2-thread-1/INFO] [STDOUT]: [info.mineshafter.datasources.MineshafterProfileAuthority:getProfile:47]: MS.getProfile: {"username":"JakobKarde","skin":"http://oi58.tinypic.com/f9qpeb.jpg"}
[18:09:27] [pool-2-thread-1/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.net.MalformedURLException: unknown protocol: rawhttp
[18:09:27] [pool-2-thread-1/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at java.net.URL.<init>(Unknown Source)
[18:09:27] [pool-2-thread-1/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at java.net.URL.<init>(Unknown Source)
[18:09:27] [pool-2-thread-1/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at info.mineshafter.intercept.TextureHandler.addSkin(TextureHandler.java:89)
[18:09:27] [pool-2-thread-1/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at info.mineshafter.datasources.MineshafterProfileAuthority.getProfile(MineshafterProfileAuthority.java:63)
[18:09:27] [pool-2-thread-1/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at info.mineshafter.storage.Profiles.byId(Profiles.java:74)
[18:09:27] [pool-2-thread-1/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at info.mineshafter.intercept.ProfileHandler.getProfile(ProfileHandler.java:75)
[18:09:27] [pool-2-thread-1/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at info.mineshafter.intercept.ProfileHandler.handle(ProfileHandler.java:51)
[18:09:27] [pool-2-thread-1/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at info.mineshafter.hacks.URLConnectionAdapter.doRequest(URLConnectionAdapter.java:43)
[18:09:27] [pool-2-thread-1/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at info.mineshafter.hacks.URLConnectionAdapter.getInputStream(URLConnectionAdapter.java:59)
[18:09:27] [pool-2-thread-1/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at com.mojang.authlib.HttpAuthenticationService.performGetRequest(HttpAuthenticationService.java:126)
[18:09:27] [pool-2-thread-1/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:54)
[18:09:27] [pool-2-thread-1/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:175)
[18:09:27] [pool-2-thread-1/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService$1.load(YggdrasilMinecraftSessionService.java:59)
[18:09:27] [pool-2-thread-1/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService$1.load(YggdrasilMinecraftSessionService.java:56)
[18:09:27] [pool-2-thread-1/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
[18:09:27] [pool-2-thread-1/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
[18:09:27] [pool-2-thread-1/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
[18:09:27] [pool-2-thread-1/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
[18:09:27] [pool-2-thread-1/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
[18:09:27] [pool-2-thread-1/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
[18:09:27] [pool-2-thread-1/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
[18:09:27] [pool-2-thread-1/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827)
[18:09:27] [pool-2-thread-1/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:165)
[18:09:27] [pool-2-thread-1/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at net.minecraft.client.resources.SkinManager$3.run(SourceFile:106)
[18:09:27] [pool-2-thread-1/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[18:09:27] [pool-2-thread-1/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at java.util.concurrent.FutureTask.run(Unknown Source)
[18:09:27] [pool-2-thread-1/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[18:09:27] [pool-2-thread-1/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[18:09:27] [pool-2-thread-1/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at java.lang.Thread.run(Unknown Source)
[18:09:27] [pool-2-thread-1/INFO] [STDOUT]: [info.mineshafter.storage.Profiles:byId:84]: getProfileById(023b57e6c8738d474909cb04588c0f32) = http://textures.minecraft.net/texture/023b57e6c8738d474909cb04588c0f3281182f828ceb61251433d8f001760
[18:09:27] [pool-2-thread-1/INFO] [STDOUT]: [info.mineshafter.intercept.ProfileHandler:getProfile:89]: {"timestamp":1458169767230,"profileId":"023b57e6c8738d474909cb04588c0f32","profileName":"JakobKarde","isPublic":true,"textures":{"SKIN":{"url":"http://textures.minecraft.net/texture/023b57e6c8738d474909cb04588c0f3281182f828ceb61251433d8f001760"},"CAPE":{"url":null}}}
[18:09:27] [pool-2-thread-1/INFO] [STDOUT]: [info.mineshafter.intercept.ProfileHandler:getProfile:107]: {"id":"023b57e6c8738d474909cb04588c0f32","name":"JakobKarde","properties":[{"name":"textures","value":"eyJ0aW1lc3RhbXAiOjE0NTgxNjk3NjcyMzAsInByb2ZpbGVJZCI6IjAyM2I1N2U2Yzg3MzhkNDc0OTA5Y2IwNDU4OGMwZjMyIiwicHJvZmlsZU5hbWUiOiJKYWtvYkthcmRlIiwiaXNQdWJsaWMiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8wMjNiNTdlNmM4NzM4ZDQ3NDkwOWNiMDQ1ODhjMGYzMjgxMTgyZjgyOGNlYjYxMjUxNDMzZDhmMDAxNzYwIn0sIkNBUEUiOnsidXJsIjpudWxsfX19","signature":"hB0DWY6wQW7sGd1/lOXeERTVi9YOxR2xCM60zj1X4aWFWCufIoeMxFFKQjHaWMEhi/yO7tuGvbbykq+jcV44vA=="}]}
[18:09:27] [pool-2-thread-1/INFO] [STDOUT]: [info.mineshafter.intercept.ProfileHandler:getProfile:73]: ProfileHandler.getProfile(023b57e6c8738d474909cb04588c0f32)
[18:09:27] [pool-2-thread-1/INFO] [STDOUT]: [info.mineshafter.storage.Profiles:byId:84]: getProfileById(023b57e6c8738d474909cb04588c0f32) = http://textures.minecraft.net/texture/023b57e6c8738d474909cb04588c0f3281182f828ceb61251433d8f001760
[18:09:27] [pool-2-thread-1/INFO] [STDOUT]: [info.mineshafter.intercept.ProfileHandler:getProfile:89]: {"timestamp":1458169767246,"profileId":"023b57e6c8738d474909cb04588c0f32","profileName":"JakobKarde","isPublic":true,"textures":{"SKIN":{"url":"http://textures.minecraft.net/texture/023b57e6c8738d474909cb04588c0f3281182f828ceb61251433d8f001760"},"CAPE":{"url":null}}}
[18:09:27] [pool-2-thread-1/INFO] [STDOUT]: [info.mineshafter.intercept.ProfileHandler:getProfile:107]: {"id":"023b57e6c8738d474909cb04588c0f32","name":"JakobKarde","properties":[{"name":"textures","value":"eyJ0aW1lc3RhbXAiOjE0NTgxNjk3NjcyNDYsInByb2ZpbGVJZCI6IjAyM2I1N2U2Yzg3MzhkNDc0OTA5Y2IwNDU4OGMwZjMyIiwicHJvZmlsZU5hbWUiOiJKYWtvYkthcmRlIiwiaXNQdWJsaWMiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8wMjNiNTdlNmM4NzM4ZDQ3NDkwOWNiMDQ1ODhjMGYzMjgxMTgyZjgyOGNlYjYxMjUxNDMzZDhmMDAxNzYwIn0sIkNBUEUiOnsidXJsIjpudWxsfX19","signature":"NjESw4Rx0/I9uOVSQmY5cjjs87QRXYzdLQvJuspxwzjBaxkKh5YYHrV/EIiim6tc1p7rs4r3eYmxF/qrq+w6Jw=="}]}
[18:09:27] [Server thread/INFO]: JakobKarde lost connection: TextComponent{text='Disconnected', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
[18:09:27] [Server thread/INFO]: JakobKarde left the game
[18:09:27] [Server thread/INFO]: Stopping singleplayer server as player logged out
[18:09:27] [Server thread/INFO]: Stopping server
[18:09:27] [Server thread/INFO]: Saving players
[18:09:27] [Server thread/INFO]: Saving worlds
[18:09:27] [Server thread/INFO]: Saving chunks for level 'New World'/Overworld
[18:09:34] [Server thread/INFO]: Saving chunks for level 'New World'/Nether
[18:09:34] [Server thread/INFO]: Saving chunks for level 'New World'/The End
[18:09:40] [Server thread/INFO] [FML]: Unloading dimension 0
[18:09:40] [Server thread/INFO] [FML]: Unloading dimension -1
[18:09:40] [Server thread/INFO] [FML]: Unloading dimension 1
[18:09:40] [Server thread/INFO] [FML]: Applying holder lookups
[18:09:40] [Server thread/INFO] [FML]: Holder lookups applied

**Comment by Tamaized** [comment]
"info.mineshafter.hacks.InterceptHttpsHandler"
That's what caught my eye and no idea what that is. Other than that, I've got no clue sadly.

**Comment by iChun** [comment]
Yggdrasil's throwing an NPE when I try to get a game profile from a player's name. Were the MC servers down at that point? Is this still occuring?

**Comment by iChun** [comment]
Didn't notice Mineshafter in this log, huh. Thanks @Tamaized

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
