### ISSUE TITLE
When I try to morph game crashes both singleplayer and Server!

### ISSUE THREAD

**Issue by Devilswarchild** [iChun/Morph#851]
and when I try to rejoin my SP world and my server world morph crashes immediately upon load preventing the user from actually playing or continuing on so its stuck in a permanent loops. here is the error message 
`[13:02:06] [Client thread/ERROR]: There was a critical exception handling a packet on channel Morph
java.lang.NullPointerException
	at net.minecraft.client.renderer.GLAllocation.func_74523_b(SourceFile:23) ~[ban.class:?]
	at morph.client.model.ModelHelper.compileRenderableModels(ModelHelper.java:564) ~[ModelHelper.class:?]
	at morph.client.model.ModelMorph.<init>(ModelMorph.java:44) ~[ModelMorph.class:?]
	at morph.client.morph.MorphInfoClient.<init>(MorphInfoClient.java:37) ~[MorphInfoClient.class:?]
	at morph.common.packet.PacketMorphInfo.handleClient(PacketMorphInfo.java:158) ~[PacketMorphInfo.class:?]
	at morph.common.packet.PacketMorphInfo.execute(PacketMorphInfo.java:100) ~[PacketMorphInfo.class:?]
	at ichun.common.core.network.ChannelHandler$PacketExecuter.channelRead0(ChannelHandler.java:84) ~[ChannelHandler$PacketExecuter.class:?]
	at ichun.common.core.network.ChannelHandler$PacketExecuter.channelRead0(ChannelHandler.java:66) ~[ChannelHandler$PacketExecuter.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Unknown Source) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Unknown Source) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Unknown Source) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[13:02:06] [Netty Client IO #4/INFO]: Restoring client configs.`

please fix this asap

[log.txt](https://github.com/iChun/Morph/files/1078544/log.txt)

**Comment by Devilswarchild** [comment]
[log.txt](https://github.com/iChun/Morph/files/1078540/log.txt)

**Comment by sudo-apt-get-install** [comment]
Morph Mod is deader than the dinosaurs.

Try [Metamorph](https://minecraft.curseforge.com/projects/metamorph)

**Comment by Devilswarchild** [comment]
metamorph has nothing for 1.7.10 btw so thats not even viable

**Comment by sudo-apt-get-install** [comment]
1.7.10 is also dead, it's time to move on.

**Comment by Devilswarchild** [comment]
its not dead seeing as half of all the greatest mods haven't even ported to 1.10.2+ yet...so how dare you say its dead

**Comment by Tamaized** [comment]
There's a 1.10.2 branch as well

**Comment by iChun** [comment]
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.
