### ISSUE TITLE
[Incompatibility/crash] Astral sorcery flares

### ISSUE THREAD

**Issue by Austin5003** [iChun/Morph#889]
[crash-2017-11-20_19.16.01-client (Morph).txt](https://github.com/iChun/Morph/files/1489564/crash-2017-11-20_19.16.01-client.Morph.txt)

**Comment by iChun** [comment]
java.lang.ClassCastException: hellfirepvp.astralsorcery.client.render.entity.RenderEntityFlare cannot be cast to net.minecraft.client.renderer.entity.RenderLivingBase
	at me.ichun.mods.morph.client.render.RenderMorphAcquisition.doRender(RenderMorphAcquisition.java:53)
	at me.ichun.mods.morph.client.render.RenderMorphAcquisition.func_76986_a(RenderMorphAcquisition.java:22)
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:384)

I can recommend blacklisting the entity as a morph for now. The fix will hopefully be in the next update.

**Comment by iChun** [comment]
Fixed for next update.
