### ISSUE TITLE
Crash when loading Villager NBT

### ISSUE THREAD

**Issue by AlphaTrooperY** [iChun/Morph#894]
An Entity minecraft:villager(Villager) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
net.minecraft.util.ReportedException: Loading entity NBT
	at net.minecraft.entity.Entity.func_70020_e(Entity.java:1874)
	at net.minecraft.entity.EntityList.func_75615_a(EntityList.java:220)
	at me.ichun.mods.morph.common.morph.MorphVariant.createEntityInstance(MorphVariant.java:84)
	at me.ichun.mods.morph.common.morph.MorphState.getEntInstance(MorphState.java:28)
	at me.ichun.mods.morph.client.core.EventHandlerClient.onClientTick(EventHandlerClient.java:829)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1026_EventHandlerClient_onClientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:347)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1909)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.RuntimeException: Attempted to set villager profession to unregistered profession: 6 null
	at net.minecraftforge.fml.common.registry.VillagerRegistry.onSetProfession(VillagerRegistry.java:334)
	at net.minecraft.entity.passive.EntityVillager.func_184206_a(EntityVillager.java:457)
	at net.minecraft.network.datasync.EntityDataManager.func_187227_b(SourceFile:125)
	at net.minecraft.entity.passive.EntityVillager.func_70938_b(EntityVillager.java:423)
	at net.minecraft.entity.passive.EntityVillager.func_70037_a(EntityVillager.java:359)
	at net.minecraft.entity.Entity.func_70020_e(Entity.java:1862)
	... 18 more

MC Version: 1.12.2
Morph Version: 7.1.0
iChunUtil Version: 7.1.2
Comments: This crash is repeatable, multiple times occurred in the same day as this issue was submitted. This error was in the MC Console (Need it open to find errors in modpacks being a modpack dev.). This will somewhat lock my survival world until fixed. Also, I was crossing dimensions (Aroma1997's Mining Dim to Overworld) when this occurred. Can you set this as a high priority so I can continue my world quickly? Thanks for the reply.

**Comment by iChun** [comment]
Did you have any mods that had villager professions at first but then eventually removed them?

**Comment by AlphaTrooperY** [comment]
Not that I know of.

**Comment by iChun** [comment]
The exception should have been handled and the Morph would have been marked as invalid.

**Comment by iChun** [comment]
Are you actually crashing or is this just being printed out to the console?

**Comment by AlphaTrooperY** [comment]
It is printing out in the console and crashes soon after.

**Comment by iChun** [comment]
are you sure the crash afterwards is a Morph crash? Wouldn't that be a different stack trace? I'd like to see your full log

**Comment by AlphaTrooperY** [comment]
QQ: is there any way to delete morphs in a world?

**Comment by AlphaTrooperY** [comment]
through the files? (Not In Game, but through file explorer)

**Comment by iChun** [comment]
/morph clear <player name> is the only way

**Comment by iChun** [comment]
yes I want the full log.

**Comment by iChun** [comment]
You shouldn't be crashing. If this prints out to the console then you get a crash shortly afterwards, I doubt it's Morph's fault.

**Comment by AlphaTrooperY** [comment]
Unable to find a crash log in the crash logs folder.

**Comment by AlphaTrooperY** [comment]
for 11/22/2017.

**Comment by iChun** [comment]
If you can't find me the logs then I cannot help you out with this issue. I'm fairly sure you shouldn't be crashing from this error.

**Comment by AlphaTrooperY** [comment]
I think a recommendation is to add an external way to delete morphs.

**Comment by iChun** [comment]
Errornous morphs should be handled without crashing. Again, I don't think you're crashing because of this and if you can't show me the logs I can't tell you what's causing it.

**Comment by AlphaTrooperY** [comment]
Boss morphs are turned off.

**Comment by iChun** [comment]
If you want to delete the morphs without going ingame go edit the player's NBT. There are tools for that out there already.

**Comment by iChun** [comment]
Boss morphs mean nothing to me. I need logs.

**Comment by AlphaTrooperY** [comment]
ok.

**Comment by AlphaTrooperY** [comment]
You can now close this issue, this is now apparently gone since I updated mods.

**Comment by AlphaTrooperY** [comment]
The crash is not associated with this mod, too.
