### ISSUE TITLE
nullpointerexception crash when using a mechanical user to kill a mob.

### ISSUE THREAD

**Issue by Zer0Burn** [iChun/Morph#909]
What the title says, I was building a prototype mob grinder using mechanical users and whenever it killed a mob the game crashed and I got:

`Exception caught during firing event net.minecraftforge.event.entity.living.LivingDeathEvent@976f766:
java.lang.NullPointerException
	at me.ichun.mods.morph.common.handler.PlayerMorphHandler.acquireMorph(PlayerMorphHandler.java:264)
	at me.ichun.mods.morph.common.core.EventHandlerServer.onLivingDeath(EventHandlerServer.java:159)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_990_EventHandlerServer_onLivingDeath_LivingDeathEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:576)
	at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:1159)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:1014)
	at net.minecraft.entity.monster.EntityMob.func_70097_a(EntityMob.java:70)
	at net.minecraft.entity.monster.EntitySilverfish.func_70097_a(SourceFile:112)
	at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1328)
	at net.minecraft.entity.player.EntityPlayerMP.func_71059_n(EntityPlayerMP.java:1420)
	at com.rwtema.extrautils2.tile.TileUse.operate(TileUse.java:276)
	at com.rwtema.extrautils2.tile.TileAdvInteractor.func_73660_a(TileAdvInteractor.java:93)
	at net.minecraft.world.World.func_72939_s(World.java:1829)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by iChun** [comment]
Slated for next update.
