### ISSUE TITLE
[Bug] Going into Compact Machines while morphing 

### ISSUE THREAD

**Issue by 117MasterChief96** [iChun/Morph#911]
When you try and go into a compact machine while morphing it will crash the game.  In the console it will give the error Null pointers.  I then tried to replicate this to see if it would happen again and it did but this time it crashed the server giving no error.

**Comment by iChun** [comment]
A crash would be nice. Make sure you're on the latest version first.

**Comment by iChun** [comment]
A  crash log I meant.

**Comment by 117MasterChief96** [comment]
Here is the client crash log.  I also tried to see if I can make it crash the server again and I did but still gives no log.

Unreported exception thrown!
java.lang.NullPointerException
	at me.ichun.mods.morph.client.core.EventHandlerClient.onRenderTick(EventHandlerClient.java:798)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1009_EventHandlerClient_onRenderTick_RenderTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onRenderTickStart(FMLCommonHandler.java:353)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1115)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by joazlazer** [comment]
To add on to the context of this issue, this bug is actually a result of changing dimensions while morphing at all. This crash has occured multiple times in a (slightly) modified direwolf20 1.12 FTB pack: [Gist of crashlog](https://gist.github.com/joazlazer/dae34af81025af9724af68a31fe5071b)

**Comment by 117MasterChief96** [comment]
So it would be because I added a mod?

**Comment by iChun** [comment]
Should be fixed in 7.1.3.
