### ISSUE TITLE
Crashing Game

### ISSUE THREAD

**Issue by ZeusHaxer** [iChun/Morph#928]
when i try to kill 2 mobs and if i try to spawn mobs and take items up then the game crashes

here is the log of crash

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 1/21/18 11:52 AM
Description: Colliding entity with block

java.lang.NullPointerException: Colliding entity with block
	at net.minecraftforge.common.ForgeHooks.sendRecipeBook(ForgeHooks.java:1352)
	at net.minecraft.stats.RecipeBookServer.func_194081_a(RecipeBookServer.java:58)
	at net.minecraft.stats.RecipeBookServer.func_193835_a(RecipeBookServer.java:37)
	at net.minecraft.entity.player.EntityPlayerMP.func_192021_a(EntityPlayerMP.java:1074)
	at net.minecraft.entity.player.EntityPlayerMP.func_193102_a(EntityPlayerMP.java:1086)
	at net.minecraft.advancements.AdvancementRewards.func_192113_a(SourceFile:76)
	at net.minecraft.advancements.PlayerAdvancements.func_192750_a(SourceFile:175)
	at net.minecraft.advancements.ICriterionTrigger$Listener.func_192159_a(SourceFile:31)
	at net.minecraft.advancements.critereon.EnterBlockTrigger$Listeners.func_192471_a(SourceFile:162)
	at net.minecraft.advancements.critereon.EnterBlockTrigger.func_192193_a(SourceFile:101)
	at net.minecraft.entity.player.EntityPlayerMP.func_191955_a(EntityPlayerMP.java:306)
	at net.minecraft.entity.Entity.func_145775_I(Entity.java:1043)
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:963)
	at net.minecraft.entity.EntityLivingBase.func_191986_a(EntityLivingBase.java:1945)
	at net.minecraft.entity.player.EntityPlayer.func_191986_a(EntityPlayer.java:1815)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2380)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:511)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2166)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:232)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:179)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraftforge.common.ForgeHooks.sendRecipeBook(ForgeHooks.java:1352)
	at net.minecraft.stats.RecipeBookServer.func_194081_a(RecipeBookServer.java:58)
	at net.minecraft.stats.RecipeBookServer.func_193835_a(RecipeBookServer.java:37)
	at net.minecraft.entity.player.EntityPlayerMP.func_192021_a(EntityPlayerMP.java:1074)
	at net.minecraft.entity.player.EntityPlayerMP.func_193102_a(EntityPlayerMP.java:1086)
	at net.minecraft.advancements.AdvancementRewards.func_192113_a(SourceFile:76)
	at net.minecraft.advancements.PlayerAdvancements.func_192750_a(SourceFile:175)
	at net.minecraft.advancements.ICriterionTrigger$Listener.func_192159_a(SourceFile:31)
	at net.minecraft.advancements.critereon.EnterBlockTrigger$Listeners.func_192471_a(SourceFile:162)
	at net.minecraft.advancements.critereon.EnterBlockTrigger.func_192193_a(SourceFile:101)
	at net.minecraft.entity.player.EntityPlayerMP.func_191955_a(EntityPlayerMP.java:306)

-- Block being collided with --
Details:
	Block: minecraft:water[level=0]
	Block location: World: (-323,62,375), Chunk: (at 13,3,7 in -21,23; contains blocks -336,0,368 to -321,255,383), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Stacktrace:
	at net.minecraft.entity.Entity.func_145775_I(Entity.java:1043)

-- Entity being checked for collision --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 14
	Entity Name: ZeusHaxer
	Entity's Exact location: -322.31, 62.00, 375.49
	Entity's Block location: World: (-323,62,375), Chunk: (at 13,3,7 in -21,23; contains blocks -336,0,368 to -321,255,383), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:963)
	at net.minecraft.entity.EntityLivingBase.func_191986_a(EntityLivingBase.java:1945)
	at net.minecraft.entity.player.EntityPlayer.func_191986_a(EntityPlayer.java:1815)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2380)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:511)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2166)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:232)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 14
	Entity Name: ZeusHaxer
	Entity's Exact location: -322.31, 62.00, 375.49
	Entity's Block location: World: (-323,62,375), Chunk: (at 13,3,7 in -21,23; contains blocks -336,0,368 to -321,255,383), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@1650550
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:179)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_151, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 119905312 bytes (114 MB) / 523501568 bytes (499 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.0.2486 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                | Version      | Source                        | Signature                                |
	|:--------- |:----------------- |:------------ |:----------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft         | 1.12.2       | minecraft.jar                 | None                                     |
	| UCHIJAAAA | mcp               | 9.42         | minecraft.jar                 | None                                     |
	| UCHIJAAAA | FML               | 8.0.99.99    | forge-1.12.2-14.23.0.2486.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge             | 14.23.0.2486 | forge-1.12.2-14.23.0.2486.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | mercurius_updater | 1.0          | MercuriusUpdater-1.12.2.jar   | None                                     |
	| UCHIJAAAA | ichunutil         | 7.1.4        | iChunUtil-1.12.2-7.1.4.jar    | None                                     |
	| UCHIJAAAA | morph             | 7.1.2        | Morph-1.12.2-7.1.2.jar        | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['ZeusHaxer'/14, l='xD', x=-322.31, y=62.00, z=375.49]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by iChun** [comment]
As Morph has just been rewritten and released for MC 1.16.5, I am clearing the issue tracker as I have not provided any support Morph for 1.12.2 and earlier. My apologies for not addressing your issue.
