### ISSUE TITLE
Crash after killing mob on 1.7.10

### ISSUE THREAD

**Issue by SabaraOne** [iChun/Morph#942]
I'm running 0.9.3 on 1.7.10 with Forge 10.13.4.1614 with a whole bunch of other mods on the latest stable build of MultiMC. My list looks like

- Extended Shaders 4.1
- Metroid Cubed 3
- Agricrat
- DragonAPI/ReactorCraft/Rotarycraft/Electricraft/Chromaticraft
- Anti ID Conflict
- Applied energistics 2/Extra Cells 2
- Aroma1997 Core/Dimensional world/Backup
- cofh core/big reactors
- Buildcraft/BC Compat/BC Additions/Eureka
- CodeChickenCore/NEI/WAILA/WailaHarvestability/WailaNBT
- Another Ore Bites The Dust
- Compact Machines
- Enchanting Plus
- More Enchantments
- Extra Utilities
- Forge Multiparts
- Galacticraft Core/Planets/Micdoodle Core
- Minecraft Comes Alive/RadixCore
- Mob Amputation/Sync/Torched/iChunUtil
- Mystcraft
- OpenComputers
- OpenEye
- Optifine
- ProjectE
- Twilight Forest
- Version Checker

Every mod is up to date according to Version Checker aside from Micdoodle Core and AE2, both of which I know it's wrong about.

I only retrofitted Morph in today, and the first time I killed a mob, my singleplayer instance threw a server error and kicked me to the multipayer server select. Thee wasn't a true crash report, but when I checked the logs, I came up with this gem.
`[18:10:47] [Client thread/ERROR] [FML]: There was a critical exception handling a packet on channel Morph
java.lang.NullPointerException
	at net.minecraft.client.renderer.GLAllocation.func_74523_b(SourceFile:23) ~[ban.class:?]
	at morph.client.model.ModelHelper.getModelCubesCopy(ModelHelper.java:48) ~[ModelHelper.class:?]
	at morph.client.model.ModelMorphAcquisition.<init>(ModelMorphAcquisition.java:36) ~[ModelMorphAcquisition.class:?]
	at morph.client.entity.EntityMorphAcquisition.<init>(EntityMorphAcquisition.java:36) ~[EntityMorphAcquisition.class:?]
	at morph.common.packet.PacketMorphAcquisition.handleClient(PacketMorphAcquisition.java:87) ~[PacketMorphAcquisition.class:?]
	at morph.common.packet.PacketMorphAcquisition.execute(PacketMorphAcquisition.java:49) ~[PacketMorphAcquisition.class:?]
	at ichun.common.core.network.ChannelHandler$PacketExecuter.channelRead0(ChannelHandler.java:84) ~[ChannelHandler$PacketExecuter.class:?]
	at ichun.common.core.network.ChannelHandler$PacketExecuter.channelRead0(ChannelHandler.java:66) ~[ChannelHandler$PacketExecuter.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_141]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_141]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_141]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_141]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_141]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_141]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_141]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_141]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]`
Reloaded the world fine and attempted to kill a different animal. It kicked me with the same result and threw this. I don't know if it's the same, but I'm going to be safe and add it anyway.
`[18:35:10] [Client thread/ERROR] [FML]: There was a critical exception handling a packet on channel Morph
java.lang.NullPointerException
	at net.minecraft.client.renderer.GLAllocation.func_74523_b(SourceFile:23) ~[ban.class:?]
	at morph.client.model.ModelHelper.getModelCubesCopy(ModelHelper.java:48) ~[ModelHelper.class:?]
	at morph.client.model.ModelMorphAcquisition.<init>(ModelMorphAcquisition.java:36) ~[ModelMorphAcquisition.class:?]
	at morph.client.entity.EntityMorphAcquisition.<init>(EntityMorphAcquisition.java:36) ~[EntityMorphAcquisition.class:?]
	at morph.common.packet.PacketMorphAcquisition.handleClient(PacketMorphAcquisition.java:87) ~[PacketMorphAcquisition.class:?]
	at morph.common.packet.PacketMorphAcquisition.execute(PacketMorphAcquisition.java:49) ~[PacketMorphAcquisition.class:?]
	at ichun.common.core.network.ChannelHandler$PacketExecuter.channelRead0(ChannelHandler.java:84) ~[ChannelHandler$PacketExecuter.class:?]
	at ichun.common.core.network.ChannelHandler$PacketExecuter.channelRead0(ChannelHandler.java:66) ~[ChannelHandler$PacketExecuter.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_141]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_141]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_141]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_141]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_141]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_141]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_141]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_141]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]`
Reloading again and killing one of the mobs I already had a morph for (A cow) just killed a cow. I am able to see chicken and cow as well as myself in my morph list. Deleting cow did nothing aside from deleting cow. Morphiing into chicken threw:
`[18:42:06] [Client thread/ERROR] [FML]: There was a critical exception handling a packet on channel Morph
java.lang.NullPointerException
	at net.minecraft.client.renderer.GLAllocation.func_74523_b(SourceFile:23) ~[ban.class:?]
	at morph.client.model.ModelHelper.getModelCubesCopy(ModelHelper.java:48) ~[ModelHelper.class:?]
	at morph.client.model.ModelMorph.<init>(ModelMorph.java:46) ~[ModelMorph.class:?]
	at morph.client.morph.MorphInfoClient.<init>(MorphInfoClient.java:37) ~[MorphInfoClient.class:?]
	at morph.common.packet.PacketMorphInfo.handleClient(PacketMorphInfo.java:158) ~[PacketMorphInfo.class:?]
	at morph.common.packet.PacketMorphInfo.execute(PacketMorphInfo.java:100) ~[PacketMorphInfo.class:?]
	at ichun.common.core.network.ChannelHandler$PacketExecuter.channelRead0(ChannelHandler.java:84) ~[ChannelHandler$PacketExecuter.class:?]
	at ichun.common.core.network.ChannelHandler$PacketExecuter.channelRead0(ChannelHandler.java:66) ~[ChannelHandler$PacketExecuter.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_141]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_141]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_141]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_141]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_141]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_141]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_141]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_141]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]`
and I can no longer freely log into the world. I am tempted to blame Chromaticraft, but the only evidenc ei have for that is that I don't have evidence for anything else and absense of evidence is not evidence of absense. Removing Morph brings the modpack to full functionality aside from, of course, the loss of Morph capability. Any ideas?

EDIT: To clarify, no this is not a proper modpack, it's a slap-a-bunch-of-stuff-together-and-see-what-works collection of mods that actually seems to work pretty well.

**Comment by ArtelGG** [comment]
See #941

**Comment by iChun** [comment]
https://github.com/iChun/Morph/issues/878
