### ISSUE TITLE
Anoying Error log very strange

### ISSUE THREAD

**Issue by xprsniperz** [iChun/Morph#972]
There was a critical exception handling a packet on channel Morph
java.lang.NullPointerException
	at net.minecraft.client.renderer.GLAllocation.func_74523_b(SourceFile:23)
	at morph.client.model.ModelHelper.getModelCubesCopy(ModelHelper.java:48)
	at morph.client.model.ModelMorph.<init>(ModelMorph.java:46)
	at morph.client.morph.MorphInfoClient.<init>(MorphInfoClient.java:37)
	at morph.common.packet.PacketMorphInfo.handleClient(PacketMorphInfo.java:158)
	at morph.common.packet.PacketMorphInfo.execute(PacketMorphInfo.java:100)
	at ichun.common.core.network.ChannelHandler$PacketExecuter.channelRead0(ChannelHandler.java:84)
	at ichun.common.core.network.ChannelHandler$PacketExecuter.channelRead0(ChannelHandler.java:66)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98)
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169)
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by iChun** [comment]
You're using morph with Optifine on MC 1.7.10. They're not compatible with
each other. I'm not gonna fix this because Minecraft 1.7.10 is also over 4
years old.

**Comment by iChun** [comment]
https://github.com/iChun/Morph/issues/878
